{@include 'header.phtml'@}

<!--banner start-->
<div class="pageBanner">
    <img src="http://{@$config.host@}/{@$config.news_banner@}">
</div>
<!--banner end-->

<!--mainContent start-->
<div class="mainContent">
    <!--内容-->
    <div class="container content1">
        <!--标题-->
        <div class="pageTit">乐开分享</div>
        <!--/标题-->
        <div class="conBase">
        	<!--新闻标题-->
            <div class="innerNewsTit">{@$news.title@}</div>
            <!--新闻内容-->
            <p>{@$news.content@}</p>
            <p class="txtR">{@$news.add_time@}</p>
        	<!--/新闻内容-->
    	</div>
        <div  style="text-align: center;margin:20px;">
            <a href="/news"><span class="btn">更多分享</span></a>
        </div>
        <div class="clearboth"></div>
    </div>
    <!--/内容-->	     
</div>
<!--mainContent end-->

<script type="text/javascript">
$(function() {  
	//顶部导航 选中状态
	$(".menu dd.m4 a").addClass("current")	   
})
</script>

{@include 'footer.phtml'@}
