{@include 'header.phtml'@}

<div class="margin_head" style="background-color:#e7efef;">
    <img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.banner@}">
</div>

<div class="container padding">
    <div class="row" style="padding: 20px 0;"><h3>{@$news.title@}</h3></div>
    <div class="row" style="padding: 10px 0">
        <div class="col-6">{@$news.add_time@}</div>
        <div class="col-3">{@$news.click@}<img src="http://{@$config.host@}/img/see.png"/></div>
        <div class="col-3">{@$news.good@}<img src="http://{@$config.host@}/img/good.png"/></div>
    </div>
    <div class="row" style="background-color: #f6f6f6;padding: 30px 0;">
        <div class="col-12">{@$news.description@}</div>
    </div>
    {@if $news.img@}
    <div class="row" style="padding: 30px 0">
        <div class="col-12"><img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$news.img@}"></div>
    </div>
    {@/if@}
    <div class="row"><div class="col-12"><p>{@$news.content@}</p></div></div>
    <div class="row text-center" style="margin:20px;">
        <div class="col-12"><a href="/news"><span class="more">返回</span></a></div>
    </div>
</div>


{@include 'footer.phtml'@}

<script>

</script>
