{@include 'header.phtml'@}

<!--mainContent start-->
<div class="mainContent">
    <!--内容-->
    <div class="container content">
        <!--标题-->
        <div class="pageTit">新闻中心</div>
        <!--/标题-->
        <!--新闻列表-->
        {@foreach from=$list item=news@}
        <div class="row newsbottom">
            <div class="col-md-10">
                <a href="/news/detail/id/{@$news.id@}" class="{@$news.class@}">【新闻】{@$news.title@}</a>
            </div>
            <div class="col-md-2 fr">
                <span>{@$news.add_time@}</span>
            </div>
        </div>
        {@/foreach@}

        <!--翻页-->
        <div class="page_turn page_turnSpe txtC">
            {@$pagebar@}
        </div>
        <!--/翻页-->

        <!--/新闻列表-->
        <div class="clearboth"></div>
    </div>
    <!--/内容-->
</div>
<!--mainContent end-->

<script type="text/javascript">
$(function() {
	//顶部导航 选中状态
	$(".menu dd.m4 a").addClass("current")
})
</script>

{@include 'footer.phtml'@}
