{@include 'header.phtml'@}

<!--banner start-->
<div class="pageBanner">
    <img src="{@$config.about_banner@}">
</div>
<!--banner end-->

<!--mainContent start-->
<div class="mainContent">
    <!--内容-->
    <div class="container content1">
        <!--标题-->
        <div class="pageTit">关于乐开</div>
        <!--/标题-->
        <div class="conBase">
            <div class="text-center"><h4>*公司介绍*</h4></div>
            <hr/>
            <p>乐开音乐专注于0-12岁儿童音乐教育，致力于提升全体国民儿童的音乐素养，带给孩子最具时代审美和气质的儿童音乐，让亿万儿童享有更具艺术高度的音乐教育服务。</p>
            <div class="text-center"><h4>*创始历程*</h4></div>
            <hr/>
            <p></p>
            <div class="text-center"><h4>*人才结构*</h4></div>
            <hr/>
            <p></p>
            <div class="text-center"><h4>*企业文化*</h4></div>
            <hr/>
            <p>
                <ul class="ul-horizontal">
                    <li>愿景：</li>
                    <li>使命：</li>
                    <li>价值观：</li>
                </ul>
            </p>
        </div>
    </div>
    <!--/内容-->
</div>
<!--mainContent end-->

{@include 'footer.phtml'@}

