{@include 'header.phtml'@}

<div class="margin_head" style="background-color:#e7efef;">
    <img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.banner@}">
</div>

<div class="container marginTop1">
    <h2  class="lineHeight1">关于我们 / About us</h2>
    <div class="row">
        <div class="col-md-8">
            <p  class="lineHeight1">{@$pageConfig.description@}</p>
            <div class="row" style="margin-top: 20px">
                <div class="col-md-6">
                    <h4>愿景</h4>
                    <p  class="lineHeight1">{@$pageConfig.content_1@}</p>
                </div>
                <div class="col-md-6">
                    <h4>使命</h4>
                    <p  class="lineHeight1">{@$pageConfig.content_2@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4"><img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.img1@}"></div>
    </div>

    <div class="row marginTop1 marginBottom">
        <div class="col-8" style="padding: 0"><img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.img2@}"></div>
        <div class="col-4" style="padding: 0"><img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.img3@}"></div>
        <div class="col-4" style="padding: 0"><img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.img4@}"></div>
        <div class="col-8" style="padding: 0"><img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.img5@}"></div>
    </div>

    <h3 class="lineHeight">团队成员 / Team members</h3>

    <div class="row marginBottom" style="margin-top: 10px;">
        <div class="col-md-3 col-6">
            <div class="card">
                <img class="card-img-top carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.member1_img@}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{@$pageConfig.member1_name@}</h5>
                    <p class="card-text">{@$pageConfig.member1_description@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-6">
            <div class="card">
                <img class="card-img-top carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.member2_img@}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{@$pageConfig.member2_name@}</h5>
                    <p class="card-text">{@$pageConfig.member2_description@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-6">
            <div class="card">
                <img class="card-img-top carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.member3_img@}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{@$pageConfig.member3_name@}</h5>
                    <p class="card-text">{@$pageConfig.member3_description@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-6">
            <div class="card">
                <img class="card-img-top carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.member4_img@}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{@$pageConfig.member4_name@}</h5>
                    <p class="card-text">{@$pageConfig.member4_description@}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="background-color: #cccccc;">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3  class="lineHeight">成就梦想</h3>
                <p  class="lineHeigh1t">{@$pageConfig.content_3@}</p>
            </div>
            <div class="col-md-6" style="padding: 0;"><img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.img6@}"></div>
        </div>
    </div>
</div>

{@include 'footer.phtml'@}

