<!--{@include 'header.phtml'@}-->
<html lang="en">
<head>
    {@if isset($meta_title) AND $meta_title@}
    <title>{@$meta_title|escape:'htmlall':'UTF-8'@}</title>
    {@/if@}
    {@if isset($meta_description) AND $meta_description@}
    <meta name="description" content="{@$meta_description|escape:html:'UTF-8'@}"/>
    {@/if@}
    {@if isset($meta_keywords) AND $meta_keywords@}
    <meta name="keywords" content="{@$meta_keywords|escape:html:'UTF-8'@}"/>
    {@/if@}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
    {@if isset($css_files)@}
    {@foreach from=$css_files item=css_uri@}
    <link href="{@$css_uri@}" rel="stylesheet" type="text/css" media="all"/>
    {@/foreach@}
    {@/if@}
</head>
<body data-spy="scroll" data-target=".bs-docs-sidebar">

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div  class="background padding1">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">导航</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span style="display: block;padding:0 0 0 20px;">
                        <img src="http://{@$config.host@}/img/logosmall.png" width="50px" height="50px">
                        <a class="header-title" href="/" style="color: #fff">乐开儿童音乐王国</a>
                    </span>
            </div>
            <div id="navbar" class="navbar-collapse collapse" style="margin-top: 20px;">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/" style="color: #fff">首页</a></li>
                    <li><a href="/case" style="color: #fff">乐开作品</a></li>
                    <li><a href="/photo" style="color: #fff">乐开风采</a></li>
                    <li><a href="/news" style="color: #fff">乐开文化</a></li>
                    <li><a href="/job" style="color: #fff">加入乐开</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="header-wrapper"></div>
</nav>
<link href="./jplayer/case/jplayer.pink.flag.css" rel="stylesheet" type="text/css" media="all"/>
<style type="text/css">
    .jp-title { text-align:center}
    .jp-type-playlist { position:relative}
    .jp-playlist ul { position:absolute; top:120px; left:650px; background:#fff; width:455px; height:230px !important; font-size:0.9em;overflow-y: scroll;z-index: 50;border: 1px solid #eee;}
    .jp-playlist li {border-bottom:1px solid #eee; padding: 2px 20px;}
    .jp-video .jp-playlist ul { margin:0}
    div.jp-type-playlist div.jp-playlist li.jp-playlist-current { margin:0; background:#c6c4c4;border-bottom:1px solid #b7b7b7;border-top:1px solid #b7b7b7; }
    div.jp-type-playlist div.jp-playlist a { color:#000}
    div.jp-type-playlist div.jp-playlist a:hover { color:#F00}
    div.jp-type-playlist div.jp-playlist li.jp-playlist-current a { color:#F00}
    span.jp-artist {color:#666; margin-left:5px}
</style>
<!--mainContent start-->
<div class="mainContent">
    <div class="container content">
    <!--内容-->
<!--音乐作品欣赏-->
<div class="case" id="case1">
    <div class="caseCon">
        <div class="caseTop">
            <!--标题-->
            <div class="pageTit">游戏配乐欣赏</div>

            <!--轮播-->
            <div class="marqueeScroll" id="scroll01">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list1.list item=item@}
                        <li>
                            <a href="Javascript:void(0)" onclick ="detail(this,1, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                        {@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>
            </div>
            <!--/轮播-->

            <!--播放-->
            <div class="casePlay">
                <!--视频-->
                <div class="video fl">
                    <!--jplayer-->
                    <div id="jp_container_1" class="jp-video jp-video-270p" role="application" aria-label="media player">
                        <div class="jp-type-playlist">
                            <div id="jquery_jplayer_1" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <button class="jp-video-play-icon" role="button" tabindex="0">play</button>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                    <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                    <div class="jp-details">
                                        <div class="jp-title" aria-label="title">&nbsp;</div>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <div class="jp-volume-controls">
                                            <button class="jp-mute" role="button" tabindex="0">mute</button>
                                            <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                            <div class="jp-volume-bar">
                                                <div class="jp-volume-bar-value"></div>
                                            </div>
                                        </div>
                                        <div class="jp-controls">
                                            <button class="jp-previous" role="button" tabindex="0">previous</button>
                                            <button class="jp-play" role="button" tabindex="0">play</button>
                                            <button class="jp-stop" role="button" tabindex="0">stop</button>
                                            <button class="jp-next" role="button" tabindex="0">next</button>
                                        </div>
                                        <div class="jp-toggles">
                                            <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                            <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                            <button class="jp-full-screen" role="button" tabindex="0">full screen</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-playlist">
                                <ul>
                                    <!-- The method Playlist.displayPlaylist() uses this unordered list -->
                                    <li></li>
                                </ul>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    <!--/jplayer-->
                </div>
                <!--/视频-->

                <!--详细信息-->
                <div class="caseInfro fr">
                    <div class="caseInfro_a">
                        <p><span class="caseInfro_aTit">{@$list1.case.name@}</span><span class="caseInfro_aSty">{@$list1.case.lable@} {@$list1.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll"><span class="caseInfro_description">{@$list1.case.description@}</span></p>
                    </div>
                    <div class="line"></div>
                </div>
                <!--/详细信息-->

                <div class="clearboth"></div>
            </div>
            <!--/播放-->


            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/音乐作品欣赏-->

<!--音效制作欣赏-->
<div class="case" id="case2">
    <div class="caseCon">
        <div class="caseTop">
            <!--标题-->
            <div class="pageTit">游戏音效欣赏</div>

            <!--轮播-->
            <div class="marqueeScroll" id="scroll02">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list2.list item=item@}
                        <li>
                            <a href="Javascript:void(0)" onclick ="detail(this,2, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                        {@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>
            </div>
            <!--/轮播-->

            <!--播放-->
            <div class="casePlay">
                <!--视频-->
                <div class="video fl">
                    <!--jplayer-->
                    <div id="jp_container_2" class="jp-video jp-video-270p" role="application" aria-label="media player">
                        <div class="jp-type-playlist">
                            <div id="jquery_jplayer_2" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <button class="jp-video-play-icon" role="button" tabindex="0">play</button>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                    <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                    <div class="jp-details">
                                        <div class="jp-title" aria-label="title">&nbsp;</div>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <div class="jp-volume-controls">
                                            <button class="jp-mute" role="button" tabindex="0">mute</button>
                                            <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                            <div class="jp-volume-bar">
                                                <div class="jp-volume-bar-value"></div>
                                            </div>
                                        </div>
                                        <div class="jp-controls">
                                            <button class="jp-previous" role="button" tabindex="0">previous</button>
                                            <button class="jp-play" role="button" tabindex="0">play</button>
                                            <button class="jp-stop" role="button" tabindex="0">stop</button>
                                            <button class="jp-next" role="button" tabindex="0">next</button>
                                        </div>
                                        <div class="jp-toggles">
                                            <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                            <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                            <button class="jp-full-screen" role="button" tabindex="0">full screen</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-playlist">
                                <ul>
                                    <!-- The method Playlist.displayPlaylist() uses this unordered list -->
                                    <li></li>
                                </ul>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    <!--/jplayer-->
                </div>
                <!--/视频-->

                <!--详细信息-->
                <div class="caseInfro fr">
                    <div class="caseInfro_a">
                        <p><span class="caseInfro_aTit">{@$list2.case.name@}</span><span class="caseInfro_aSty">{@$list2.case.lable@} {@$list2.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll">{@$list2.case.description@}</p>
                    </div>
                    <div class="line"></div>
                </div>
                <!--/详细信息-->

                <div class="clearboth"></div>
            </div>
            <!--/播放-->


            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/音效制作欣赏-->

<!--配音作品欣赏-->
<div class="case" id="case3">
    <div class="caseCon">
        <div class="caseTop">
            <!--标题-->
            <div class="pageTit">游戏配音欣赏</div>

            <!--轮播-->
            <div class="marqueeScroll" id="scroll03">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list3.list item=item@}
                        <li>
                            <a href="Javascript:void(0)" onclick ="detail(this,3, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                        {@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>
            </div>
            <!--/轮播-->

            <!--播放-->
            <div class="casePlay">
                <!--视频-->
                <div class="video fl">
                    <!--jplayer-->
                    <div id="jp_container_3" class="jp-video jp-video-270p" role="application" aria-label="media player">
                        <div class="jp-type-playlist">
                            <div id="jquery_jplayer_3" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <button class="jp-video-play-icon" role="button" tabindex="0">play</button>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                    <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                    <div class="jp-details">
                                        <div class="jp-title" aria-label="title">&nbsp;</div>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <div class="jp-volume-controls">
                                            <button class="jp-mute" role="button" tabindex="0">mute</button>
                                            <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                            <div class="jp-volume-bar">
                                                <div class="jp-volume-bar-value"></div>
                                            </div>
                                        </div>
                                        <div class="jp-controls">
                                            <button class="jp-previous" role="button" tabindex="0">previous</button>
                                            <button class="jp-play" role="button" tabindex="0">play</button>
                                            <button class="jp-stop" role="button" tabindex="0">stop</button>
                                            <button class="jp-next" role="button" tabindex="0">next</button>
                                        </div>
                                        <div class="jp-toggles">
                                            <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                            <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                            <button class="jp-full-screen" role="button" tabindex="0">full screen</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-playlist">
                                <ul>
                                    <!-- The method Playlist.displayPlaylist() uses this unordered list -->
                                    <li></li>
                                </ul>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    <!--/jplayer-->
                </div>
                <!--/视频-->

                <!--详细信息-->
                <div class="caseInfro fr">
                    <div class="caseInfro_a">
                        <p><span class="caseInfro_aTit">{@$list3.case.name@}</span><span class="caseInfro_aSty">{@$list3.case.lable@} {@$list3.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll">{@$list3.case.description@}</p>
                    </div>
                    <div class="line"></div>

                </div>
                <!--/详细信息-->

                <div class="clearboth"></div>
            </div>
            <!--/播放-->


            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/配音作品欣赏-->

<!--CG视频欣赏-->
<div class="case" id="case4">
    <div class="caseCon">
        <div class="caseTop">
            <!--标题-->
            <div class="pageTit">CG视频欣赏</div>

            <!--轮播-->
            <div class="marqueeScroll" id="scroll04">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list4.list item=item@}
                        <li>
                            <a href="Javascript:void(0)" onclick ="detail(this,4, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                        {@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>
            </div>
            <!--/轮播-->

            <!--播放-->
            <div class="casePlay">
                <!--视频-->
                <div class="video fl">
                    <!--jplayer-->
                    <div id="jp_container_4" class="jp-video jp-video-270p" role="application" aria-label="media player">
                        <div class="jp-type-playlist">
                            <div id="jquery_jplayer_4" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <button class="jp-video-play-icon" role="button" tabindex="0">play</button>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                    <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                    <div class="jp-details">
                                        <div class="jp-title" aria-label="title">&nbsp;</div>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <div class="jp-volume-controls">
                                            <button class="jp-mute" role="button" tabindex="0">mute</button>
                                            <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                            <div class="jp-volume-bar">
                                                <div class="jp-volume-bar-value"></div>
                                            </div>
                                        </div>
                                        <div class="jp-controls">
                                            <button class="jp-previous" role="button" tabindex="0">previous</button>
                                            <button class="jp-play" role="button" tabindex="0">play</button>
                                            <button class="jp-stop" role="button" tabindex="0">stop</button>
                                            <button class="jp-next" role="button" tabindex="0">next</button>
                                        </div>
                                        <div class="jp-toggles">
                                            <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                            <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                            <button class="jp-full-screen" role="button" tabindex="0">full screen</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-playlist">
                                <ul>
                                    <!-- The method Playlist.displayPlaylist() uses this unordered list -->
                                    <li></li>
                                </ul>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    <!--/jplayer-->
                </div>
                <!--/视频-->

                <!--详细信息-->
                <div class="caseInfro fr">
                    <div class="caseInfro_a">
                        <p><span class="caseInfro_aTit">{@$list4.case.name@}</span><span class="caseInfro_aSty">{@$list4.case.lable@} {@$list4.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll">{@$list4.case.description@}</p>
                    </div>
                    <div class="line"></div>


                </div>
                <!--/详细信息-->

                <div class="clearboth"></div>
            </div>
            <!--/播放-->


            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/CG视频欣赏-->

<!--影视动漫欣赏-->
<div class="case" id="case5">
    <div class="caseCon">
        <div class="caseTop">
            <!--标题-->
            <div class="pageTit">影视动漫</div>

            <!--轮播-->
            <div class="marqueeScroll" id="scroll05">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list5.list item=item@}
                        <li>
                            <a href="Javascript:void(0)" onclick ="detail(this,5, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                        {@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>
            </div>
            <!--/轮播-->

            <!--播放-->
            <div class="casePlay">
                <!--视频-->
                <div class="video fl">
                    <!--jplayer-->
                    <div id="jp_container_5" class="jp-video jp-video-270p" role="application" aria-label="media player">
                        <div class="jp-type-playlist">
                            <div id="jquery_jplayer_5" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <button class="jp-video-play-icon" role="button" tabindex="0">play</button>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                    <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                    <div class="jp-details">
                                        <div class="jp-title" aria-label="title">&nbsp;</div>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <div class="jp-volume-controls">
                                            <button class="jp-mute" role="button" tabindex="0">mute</button>
                                            <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                            <div class="jp-volume-bar">
                                                <div class="jp-volume-bar-value"></div>
                                            </div>
                                        </div>
                                        <div class="jp-controls">
                                            <button class="jp-previous" role="button" tabindex="0">previous</button>
                                            <button class="jp-play" role="button" tabindex="0">play</button>
                                            <button class="jp-stop" role="button" tabindex="0">stop</button>
                                            <button class="jp-next" role="button" tabindex="0">next</button>
                                        </div>
                                        <div class="jp-toggles">
                                            <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                            <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                            <button class="jp-full-screen" role="button" tabindex="0">full screen</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-playlist">
                                <ul>
                                    <!-- The method Playlist.displayPlaylist() uses this unordered list -->
                                    <li></li>
                                </ul>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    <!--/jplayer-->
                </div>
                <!--/视频-->

                <!--详细信息-->
                <div class="caseInfro fr">
                    <div class="caseInfro_a">
                        <p><span class="caseInfro_aTit">{@$list5.case.name@}</span><span class="caseInfro_aSty">{@$list5.case.lable@} {@$list5.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll">{@$list5.case.description@}</p>
                    </div>
                    <div class="line"></div>


                </div>
                <!--/详细信息-->

                <div class="clearboth"></div>
            </div>
            <!--/播放-->


            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/影视动漫欣赏-->
    </div>
</div>

<!--copyright-->
<div style="background-color: #EEEEEE">
    <div class="container" style="padding: 20px">
        <div class="row">
            <div class="col-md-9 col-sm-9">©2017 {@$config.name@}版权所有 沪ICP备15002392号 24小时热线电话：<a href="tel:{@$config.mobile@}">{@$config.mobile@}</a></div>
            <div class="col-md-3 col-sm-3"><a href="/job" class="fr">加入乐开</a></div>
        </div>
    </div>
</div>
<!--/copyright-->

<!--[if lte IE 6]>
<script src="js/iepng.js" type="text/javascript"></script>
<script>
    DD_belatedPNG.fix('*');
</script>
<![endif]-->
<script type="text/javascript">
    //$(function() {
    //	//顶部导航 选中状态
    //	$(".menu dd.m3 a").addClass("current")
    //})
</script>
<script type="text/javascript" src="./js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="./js/bootstrap.min.js"></script>
<script type="text/javascript" src="./js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="./js/allOneScroll.js"></script>
<script type="text/javascript" src="./jplayer/jquery.jplayer.min.js"></script>
<script type="text/javascript" src="./jplayer/jplayer.playlist.min.js"></script>
<script type="text/javascript" src="./js/case.js"></script>

<!--{@include 'footer.phtml'@}-->
</body>
</html>
