{@include 'header.phtml'@}

<div style="background-color:#e7efef;margin-top: 95px;">
    <img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.banner@}">
</div>

<h3 class="text-center" style="line-height: 300%">用音乐开启孩子的时代审美</h3>

<div class="container">
    <div class="row" style="padding: 20px;">
        <div class="col-md-12">
            <ul id="myTab" class="nav nav-pills nav-justified">
                <li class="nav-item" style="margin: 20px;">
                    <a class="nav-link" href="#one" data-toggle="tab"
                       style="line-height:300%;background-color: #00a5a3">音乐启蒙</a>
                </li>
                <li class="nav-item" style="margin: 20px;">
                    <a class="nav-link" href="#two" data-toggle="tab"
                       style="line-height:300%;background-color: #00a5a3">音乐素养</a>
                </li>
                <li class="nav-item" style="margin: 20px;">
                    <a class="nav-link" href="#three" data-toggle="tab"
                       style="line-height:300%;background-color: #00a5a3">乐器学习</a>
                </li>
                <li class="nav-item" style="margin: 20px;">
                    <a class="nav-link" href="#four" data-toggle="tab"
                       style="line-height:300%;background-color: #00a5a3">合唱之旅</a>
                </li>
                <li class="nav-item" style="margin: 20px;">
                    <a class="nav-link" href="#five" data-toggle="tab"
                       style="line-height:300%;background-color: #00a5a3">乐队王国</a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade in active" id="one">
            <div class="row">
                <div class="col-md-6">
                    <h4 style="line-height:300%">音乐启蒙</h4>
                    <p style="line-height: 200%">2-4岁音乐启蒙教学系统；用趣味游戏的方式开启音乐感知之门</p>
                    <h4 style="line-height:300%">课程特色</h4>
                    <p style="line-height: 200%">
                        音乐启蒙是乐开音乐王国教研委员会历时2年，针对2-4岁宝宝及托班孩子精心打磨的启蒙课程，旨在孩子的听觉敏感期，用音乐游戏的方式开启宝宝的音乐感知能力，开发左右脑的协调性，建立良好的律动基础，而这也是未来感知音乐的基础能力。</p>
                    <h4 style="line-height:300%">课程效果</h4>
                    <p style="line-height: 200%">敏锐的听觉感知能力；良好的肢体律动及协调能力；良好的亲子关系</p>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="carousel-inner img-responsive"
                                 src="http://{@$config.host@}/images/course/1.png">
                        </div>
                    </div>
                    <div class="row text-center" style="padding:50px 0;">
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">聆听</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">感知</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">同化</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">模仿</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="two">
            <div class="row">
                <div class="col-md-6">
                    <h4 style="line-height:300%">音乐素养</h4>
                    <p style="line-height: 200%">4-6岁音乐素养教育；
                        用音乐和律动的方式提升国民儿童的音乐素养；
                        音乐素养-所谓由律动训练和音乐实践而获得的一种音乐修养；</p>
                    <h4 style="line-height:300%">课程特色</h4>
                    <p style="line-height: 200%">
                        LK课程内容涵盖读谱、视唱听音、节奏训练、乐器合奏，音乐赏析等多方面的综合理论基础，用音乐律动的方式帮助儿童一起建立良好的节奏级音准能力，其中所有儿歌作品词曲编配全部进行原创。</p>
                    <h4 style="line-height:300%">课程效果</h4>
                    <p style="line-height: 200%">良好的音乐审美；良好的艺术感知力；良好的节奏感及音准能力；未来学习音乐以及乐器将不再轻易放弃</p>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="carousel-inner img-responsive"
                                 src="http://{@$config.host@}/images/course/2.jpg">
                        </div>
                    </div>
                    <div class="row text-center" style="padding:50px 0;">
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">思考</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">参与</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">交互</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">创造</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="three">
            <div class="row">
                <div class="col-md-6">
                    <h4 style="line-height:300%">乐器学习</h4>
                    <p style="line-height: 200%">6-12岁乐器学习，用最钟爱的乐器去感知音乐的真谛</p>
                    <h4 style="line-height:300%">课程特色</h4>
                    <p style="line-height: 200%">在传统乐器学习基础之上，结合英国rock
                        school考级研发的专门针对现代音乐的学习体系，旨在让孩子们学习乐器不再感受枯燥，而是学以致用，本着务实快乐的方式感受音乐真正的魅力。</p>
                    <h4 style="line-height:300%">课程效果</h4>
                    <p style="line-height: 200%">乐器学习的阶段性成果明显；极好的实用性；随时保持对乐器学习良好的兴趣度；良好的音乐理解能力</p>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="carousel-inner img-responsive"
                                 src="http://{@$config.host@}/images/course/3.png">
                        </div>
                    </div>
                    <div class="row text-center" style="padding:50px 0;">
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">体会</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">畅想</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">行动</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">释放</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="four">
            <div class="row">
                <div class="col-md-6">
                    <h4 style="line-height:300%">合唱之旅</h4>
                    <p style="line-height: 200%">5-9岁儿童合唱，天籁之音就此开启，美妙童声演绎经典</p>
                    <h4 style="line-height:300%">课程特色</h4>
                    <p style="line-height: 200%">
                        乐开合唱团是乐开音乐教委会针对5-9岁孩子研发的合唱教学体系，希望让中国的孩子拥有专业的声唱培养，尤其针对过往的经典作品全部进行全新编配，让音乐更符合现代的时代审美，让孩子能拥有国际化的审美能力及作品演唱。</p>
                    <h4 style="line-height:300%">课程效果</h4>
                    <p style="line-height: 200%">良好的节奏及音准能力；专业的发声及气息控制；优秀的舞台表现能力；个体自信心的培养；良好的艺术审美</p>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="carousel-inner img-responsive"
                                 src="http://{@$config.host@}/images/course/4.png">
                        </div>
                    </div>
                    <div class="row text-center" style="padding:50px 0;">
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">自如</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">控制</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">稳定</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">情绪</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="five">
            <div class="row">
                <div class="col-md-6">
                    <h4 style="line-height:300%">乐队王国</h4>
                    <p style="line-height: 200%">8-12岁亲子乐队；没错，我们可以组乐队了，甚至可以和爸爸妈妈一起真正的享受音乐</p>
                    <h4 style="line-height:300%">课程特色</h4>
                    <p style="line-height: 200%">
                        亲子家庭乐队是乐开音乐王国的最高呈现形式，旨在孩子们及家庭拥有良好的音乐能力及乐器基础之上，进行的音乐最高形态的结合，为成员们定制的不同梯度的乐队练习曲目，定制化的总谱及伴奏体系，系统的音乐讲解，全面的音乐知识分享，让父母和孩子一起因为音乐而牵手腾飞。</p>
                    <h4 style="line-height:300%">课程效果</h4>
                    <p style="line-height: 200%">自我展示能力的培养；和睦的家庭亲子关系；舞台及演讲能力，领导力的培养；极好的音乐专综合能力； 扩充音乐及艺术视野</p>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="carousel-inner img-responsive"
                                 src="http://{@$config.host@}/images/course/5.png">
                        </div>
                    </div>
                    <div class="row text-center" style="padding:50px 0;">
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">成长</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">快乐</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">互动</span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">情感</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{@include 'footer.phtml'@}

<script>
  $(function () {
    $('#myTab li:eq(0) a').tab('show');
  });
</script>