<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
		<title>乐开音乐</title>
			<meta name="description" content="乐开音乐是专注于ACG音乐创作的专业音乐公司，公司成立于2011年，团队成员均为业内资深音乐制作人及音乐教师，公司音乐团队为诸多客户及中国亿万儿童创作数首经典的主题歌曲及动漫游戏音乐，团队专注于经典音乐的创作及传承，希望以最专业的服务结合具有艺术高度的音乐感动每一位用户！"/>
			<meta name="keywords" content="游戏音乐视频外包"/>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
			<link href="http://192.168.1.200/css/index.css" rel="stylesheet" type="text/css" media="all"/>
		</head>
<body>

<!--header start-->
<div class="header">
    <div class="inner">
    	<!--logo-->
    	<div class="logo fl"><a href="/index" title="乐开音乐网">logo</a></div>

        <!--menu-->
        <div class="menu fr">
        	<dl>
            	<dd class="m1"><a href="/#banner">首页</a></dd>
                <dd class="m2"><a href="/#service">服务</a></dd>
                <dd class="m3"><a href="/case">作品</a></dd>
                <dd class="m4"><a href="/news">动态</a></dd>
                <dd class="m5"><a href="/#aboutUs">关于</a></dd>
                <dd class="m6"><a href="/#contact">联系</a></dd>
            </dl>
        </div>
        <!--/menu-->

        <div class="clearboth"></div>
    </div>
</div>
<!--header end-->

<!--mainContent start-->
<div class="mainContent">
    <!--内容-->
    <div class="content">
    	<div class="contentTop">
        <!--标题-->
        <div class="pageTit">加入我们</div>
        <!--/标题-->
        <div class="conBase">
			{@foreach from=$list item=job@}
                <p><h5>{@$job.title@}</h5><hr/>{@$job.content@}</p>
            {@/foreach@}

        </div>
    	</div>
        <div class="clearboth"></div>
        <div class="contentBot"></div>
    </div>
    <!--/内容-->
</div>
<!--mainContent end-->

		<script type="text/javascript" src="http://192.168.1.200/js/jquery1.4.2.min.js"></script>
		<script type="text/javascript" src="http://192.168.1.200/js/jquery.base.js"></script>
{@include 'footer.phtml'@}

