	{@if isset($js_files)@}
	{@foreach from=$js_files item=js_uri@}
	<script type="text/javascript" src="{@$js_uri@}"></script>
	{@/foreach@}
	{@/if@}
	<script type="text/javascript" src="http://192.168.1.200/jplayer/jplayer.playlist.min.js"></script>
<!--copy start-->
<div class="footer"> 
    <div class="inner">
       <p class="txtC">24小时热线电话：13917605543</p>	
       <p class="txtC">乐开音乐All Rights Reserved.</p>
	   <p class="txtC"><a href="/job">加入我们</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.miitbeian.gov.cn" target='_blank'>沪ICP备15002392号</a></p>
    </div>
</div>
<!--copy end--> 

</body>
</html>
