<!--header-->
{@include 'header.phtml'@}
<!--/header-->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <!--menu-->
            {@include 'menu.phtml'@}
            <!--/menu-->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">修改招聘</h2>
            <div class="row placeholders">
                <h4><a href="/admin/job/index">返回</a></h4>
            </div>
            <div class="table-responsive">
                <form id='form' enctype="multipart/form-data" method="post" action="/admin/job/save">
                    <table class="table table-striped">
                        <tr>
                            <td>职位名称</td>
                            <td><input name="id" type="hidden" value='{@$job.id@}'/><input name="title" type="text"
                                                                                           value='{@$job.title@}'/></td>
                        </tr>
                        <tr>
                        <tr>
                            <td>职位要求</td>
                            <td>
                                <script id="content" name="content" style="width:600px;height:400px" type="text/plain">
                                    {@$job.content@}
                                </script>
                            </td>
                        </tr>
                        <tr>
                            <td colspan=2><input id='submit' type="submit" value="提交"/> <input id='reset' type="reset"
                                                                                               value="重置"/></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    //加载公式编辑器
    var this_title = UE.getEditor('content');

    //试题添加
    $('#submit').click(function () {
        var title = this_title.overflow ? '--overflow--' : this_title.getContent();
        if (title == '') {
            alert('请填写内容！');
            return false;
        } else if (title == '--overflow--') {
            alert('内容字数超限！');
            return false;
        }
        $('#form').submit();
    });

    //重置
    $('#reset').click(function () {
        this_title.setContent('');
    });

</script>
<!--footer-->
{@include 'footer.phtml'@}
<!--/footer-->
