<!--header-->
{@include 'header.phtml'@}
<!--/header-->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <!--menu-->
            {@include 'menu.phtml'@}
            <!--/menu-->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">招聘中心</h2>
            <div class="row placeholders">
                <div class="col-xs-6 col-sm-3 placeholder">
                    <a href="/admin/job/add"><button class="btn btn-primary">增加招聘</button></a>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <a href="/admin/index/main"><button class="btn btn-default">返回</button></a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>标题</th>
                        <th>发布时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {@foreach from=$list item=job@}
                    <tr>
                        <td>{@$job.id@}</td>
                        <td>{@$job.title@}</td>
                        <td>{@$job.add_time@}</td>
                        <td>
                            <a href="/admin/job/edit/?id={@$job.id@}"><button class="btn btn-primary">修改</button></a>
                            <a href="/admin/job/del/?id={@$job.id@}"><button class="btn btn-danger">删除</button></a>
                        </td>
                    </tr>
                    {@/foreach@}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--footer-->
{@include 'footer.phtml'@}
<!--/footer-->
