<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=gb2312"/>
    <title>乐开音乐网</title>
    <meta http-equiv="keywords" content=""/>
    <meta http-equiv="description" content="#"/>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
    <link href="css/index.css" type="text/css" rel="stylesheet"/>
    <script src="./js/jquery-3.2.1.min.js"></script>
</head>

<body>

<!--header start-->
<div class="header">
    <div class="inner">
        <!--logo-->
        <div class="logo fl"><a href="index.html" title="乐开音乐网">logo</a></div>

        <!--menu-->
        <div class="menu fr">
            <dl>
                <dd class="m1"><a href="#banner">首页</a></dd>
                <dd class="m2"><a href="#service">服务</a></dd>
                <dd class="m3"><a href="/case">作品</a></dd>
                <dd class="m4"><a href="/news">动态</a></dd>
                <dd class="m5"><a href="#aboutUs">关于</a></dd>
                <dd class="m6"><a href="#contact">联系</a></dd>
            </dl>
        </div>
        <!--/menu-->

        <div class="clearboth"></div>
    </div>
</div>
<!--header end-->