<!--header-->
{@include 'header.phtml'@}
<!--/header-->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <!--menu-->
            {@include 'menu.phtml'@}
            <!--/menu-->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">新增图片</h2>
            <div class="row placeholders">
                <a href="/admin/photo/index"><button class="btn btn-default">返回</button></a>
            </div>
            <div class="table-responsive">
                <form id='form' enctype="multipart/form-data" method="post" action="/admin/photo/save">
                    <table class="table table-striped">
                        <tr>
                            <td>图片名称</td>
                            <td><input name="title" type="text"/></td>
                        </tr>
                        <tr>
                        <tr>
                            <td>图片描述</td>
                            <td><textarea name="content" rows="5" cols="80"></textarea></td>
                        </tr>
                        <tr>
                            <td>资源</td>
                            <td><input name="img[]" type="file"/></td>
                        </tr>
                        <tr>
                            <td colspan=2><input id='submit' type="submit" value="提交"/> <input id='reset' type="reset"
                                                                                               value="重置"/></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

<!--footer-->
{@include 'footer.phtml'@}
<!--/footer-->
