<!--header-->
{@include 'header.phtml'@}
<!--/header-->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <!--menu-->
            {@include 'menu.phtml'@}
            <!--/menu-->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">图片中心</h2>
            <div class="row placeholders">
                <div class="col-xs-6 col-sm-3 placeholder">
                    <h4><a href="/admin/photo/add">增加图片</a></h4>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <h4><a href="/admin/index/main">返回</a></h4>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>标题</th>
                        <th>图片</th>
                        <th>发布时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {@foreach from=$list item=photo@}
                    <tr>
                        <td>{@$photo.id@}</td>
                        <td>{@$photo.title@}</td>
                        <td><img src="{@$photo.title@}" width="100px"/></td>
                        <td>{@$photo.add_time@}</td>
                        <td><a href="/admin/photo/edit/?id={@$photo.id@}">修改</a> | <a
                                    href="/admin/photo/del/?id={@$photo.id@}">删除</a></td>
                    </tr>
                    {@/foreach@}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--footer-->
{@include 'footer.phtml'@}
<!--/footer-->
