{@include 'header.phtml'@}

<!--mainContent start-->
<div class="mainContent">
    <!--内容-->
    <div class="content">
    	<div class="contentTop">
        <!--标题-->
        <div class="pageTit">新闻中心</div>
        <!--/标题-->
        <div class="conBase">
        	<!--新闻标题-->
            <div class="innerNewsTit">{@$news.title@}</div>
            <!--新闻内容-->
            <p>{@$news.content@}</p>
            
            
            <p class="txtR">{@$news.add_time@}</p>
        	<!--/新闻内容-->
    	</div>
        <div class="clearboth"></div>
        <div class="contentBot"></div>
    </div>
    <!--/内容-->	     
</div>
<!--mainContent end-->

<script type="text/javascript">
$(function() {  
	//顶部导航 选中状态
	$(".menu dd.m4 a").addClass("current")	   
})
</script>

{@include 'footer.phtml'@}
