{@include 'header.phtml'@}

<!--mainContent start-->
<div class="mainContent">
    <!--内容-->
    <div class="content">
    	<div class="contentTop">
        <!--标题-->
        <div class="pageTit">新闻中心</div>
        <!--/标题-->
        <div class="conBase">
            <!--新闻列表-->
            <ul class="newslist newslistInner">
            {@foreach from=$list item=news@}
                <li><a href="/news/detail/id/{@$news.id@}" class="{@$news.class@}">【新闻】{@$news.title@}</a><span>{@$news.add_time@}</span></li>
            {@/foreach@}
            </ul>
                
            <div class="clearboth"></div>
            
            <!--翻页-->
            <div class="page_turn page_turnSpe txtC">
                {@$pagebar@}
            </div>
            <!--/翻页-->
        </div>
        
        <!--/新闻列表-->
    	</div>
        <div class="clearboth"></div>
        <div class="contentBot"></div>
    </div>
    <!--/内容-->	     
</div>
<!--mainContent end-->

<script type="text/javascript">
$(function() {  
	//顶部导航 选中状态
	$(".menu dd.m4 a").addClass("current")
})
</script>

{@include 'footer.phtml'@}
