<div class="background2">
    <div class="container text-center">
        <h2 style="color: white;line-height: 300%">乐开儿童音乐王国全国加盟，即将开启，敬请期待</h2>
    </div>
</div>
<div class="background3">
    <div class="container" style="padding: 20px">
        <div class="row">
            <div class="col-md-9 col-sm-9">©2017 {@$config.name@}版权所有 沪ICP备15002392号 24小时热线电话：<a href="tel:{@$config.mobile@}">{@$config.mobile@}</a></div>
            <div class="col-md-3 col-sm-3"><a href="/job" class="fr">加入乐开</a></div>
        </div>
    </div>
</div>
{@if isset($js_files)@}
{@foreach from=$js_files item=js_uri@}
<script type="text/javascript" src="{@$js_uri@}"></script>
{@/foreach@}
{@/if@}
</body>
</html>
