<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div><img class="carousel-inner img-responsive" src="http://{@$config.host@}/images/index/b.jpg"/></div>
			<div>
				<h5>乐开儿童音乐王国</h5>
				<p>©2017 {@$config.name@}版权所有 沪ICP备15002392号</p>
			</div>			
		</div>
		<div class="col-md-6" style="background-color: #e6e3de">待定</div>
	</div>
</div>
</body>
{@if isset($js_files)@}
{@foreach from=$js_files item=js_uri@}
<script type="text/javascript" src="{@$js_uri@}"></script>
{@/foreach@}
{@/if@}
</html>
