<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div><img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$config.foot_img@}"/></div>
			<div>
				<h5>{@$config.title@}</h5>
				<h6><a href="tel:021-33283766">服务热线：021-33283766</a></h6>
				<p>©2017 {@$config.name@}版权所有 沪ICP备18002379号</p>
			</div>			
		</div>
		<div class="col-md-6" style="background-color: #e6e3de"></div>
	</div>
</div>
</body>
{@if isset($js_files)@}
{@foreach from=$js_files item=js_uri@}
<script type="text/javascript" src="{@$js_uri@}"></script>
{@/foreach@}
{@/if@}
</html>
