<!doctype html>
<html lang="en">
<head>
    {@if isset($meta_title) AND $meta_title@}
    <title>{@$meta_title|escape:'htmlall':'UTF-8'@}</title>
    {@/if@}
    {@if isset($meta_description) AND $meta_description@}
    <meta name="description" content="{@$meta_description|escape:html:'UTF-8'@}"/>
    {@/if@}
    {@if isset($meta_keywords) AND $meta_keywords@}
    <meta name="keywords" content="{@$meta_keywords|escape:html:'UTF-8'@}"/>
    {@/if@}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, minimum-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge，chrome=1">
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
    {@if isset($css_files)@}
    {@foreach from=$css_files item=css_uri@}
    <link href="{@$css_uri@}" rel="stylesheet" type="text/css" media="all"/>
    {@/foreach@}
    {@/if@}
    <script src="http://{@$config.host@}/js/jquery-3.2.1.min.js"></script>
</head>
<body data-spy="scroll" data-target=".bs-docs-sidebar">

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">导航</span>
                <span class="icon-bar"></span>
            </button>
            <span style="display: block;">
                <a class="" href="/">乐开音乐王国</a>
            </span>
        </div>
        <div id="navbar" class="navbar-collapse collapse">1
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/" >首页</a></li>
                <li><a href="/case">乐开课程</a></li>
                <li><a href="/photo">活动剪影</a></li>
                <li><a href="/news">乐开分享</a></li>
                <li><a href="/job">关于我们</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="clearboth"></div>