<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    {@if isset($meta_title) AND $meta_title@}
    <title>{@$meta_title|escape:'htmlall':'UTF-8'@}</title>
    {@/if@}
    {@if isset($meta_description) AND $meta_description@}
    <meta name="description" content="{@$meta_description|escape:html:'UTF-8'@}"/>
    {@/if@}
    {@if isset($meta_keywords) AND $meta_keywords@}
    <meta name="keywords" content="{@$meta_keywords|escape:html:'UTF-8'@}"/>
    {@/if@}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
    {@if isset($css_files)@}
    {@foreach from=$css_files item=css_uri@}
    <link href="{@$css_uri@}" rel="stylesheet" type="text/css" media="all"/>
    {@/foreach@}
    {@/if@}
    <script src="./js/jquery-3.2.1.min.js"></script>
</head>
<body>

<!--header start-->
<div class="header">
    <div class="inner">
        <!--logo-->
        <div class="logo fl"><a href="index.html" title="乐开音乐网">logo</a></div>

        <!--menu-->
        <div class="menu fr">
            <dl>
                <dd class="m1"><a href="/#banner">首页</a></dd>
                <dd class="m2"><a href="/#service">服务</a></dd>
                <dd class="m3"><a href="/case">作品</a></dd>
                <dd class="m4"><a href="/news">动态</a></dd>
                <dd class="m5"><a href="/#aboutUs">关于</a></dd>
                <dd class="m6"><a href="/#contact">联系</a></dd>
            </dl>
        </div>
        <!--/menu-->

        <div class="clearboth"></div>
    </div>
</div>
<!--header end-->