<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    {@if isset($meta_title) AND $meta_title@}
    <title>{@$meta_title|escape:'htmlall':'UTF-8'@}</title>
    {@/if@}
    {@if isset($meta_description) AND $meta_description@}
    <meta name="description" content="{@$meta_description|escape:html:'UTF-8'@}"/>
    {@/if@}
    {@if isset($meta_keywords) AND $meta_keywords@}
    <meta name="keywords" content="{@$meta_keywords|escape:html:'UTF-8'@}"/>
    {@/if@}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
    {@if isset($css_files)@}
    {@foreach from=$css_files item=css_uri@}
    <link href="{@$css_uri@}" rel="stylesheet" type="text/css" media="all"/>
    {@/foreach@}
    {@/if@}
    <script src="./js/jquery-3.2.1.min.js"></script>
</head>
<body data-spy="scroll" data-target=".bs-docs-sidebar">

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid" style="background-color:#4a86c3">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">导航</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" style="color: white;height: auto;font-size: x-large;line-height: 120%">乐开儿童音乐王国</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/" style="color: white;">首页</a></li>
                <li><a href="/case" style="color: white;">乐开作品</a></li>
                <li><a href="/photo" style="color: white;">乐开风采</a></li>
                <li><a href="/news" style="color: white;">乐开文化</a></li>
                <li><a href="/job" style="color: white;">加入乐开</a></li>
            </ul>
        </div>
    </div>
    <div class="header-wrapper"></div>
</nav>
<div class="clearboth"></div>