<!--header-->
{@include 'header.phtml'@}
<!--/header-->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <!--menu-->
            {@include 'menu.phtml'@}
            <!--/menu-->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">密码修改</h2>
            <div class="table-responsive">
                <form enctype="multipart/form-data" method="post" action="/admin/index/adminsave">
                    <table class="table table-striped">
                        <tr>
                            <td>用户名</td>
                            <td><input name="name" type="text" value="{@$admin.name@}" disabled="disabled"/></td>
                        </tr>
                        <tr>
                            <td>旧密码</td>
                            <td><input name="password" type="password"/></td>
                        </tr>
                        <tr>
                            <td>新密码</td>
                            <td><input name="newpassword" type="password"/></td>
                        </tr>
                        <tr>
                            <td>确认密码</td>
                            <td><input name="confirmpassword" type="password"/></td>
                        </tr>
                        <tr>
                            <td colspan=2><input type="submit" value="提交"/> <input type="reset" value="重置"/></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

<!--footer-->
{@include 'footer.phtml'@}
<!--/footer-->
