{@include 'header.phtml'@}

<!--mainContent start-->
<div class="mainContent">
    <!--内容-->
    <div class="container content">
            <!--标题-->
            <div class="pageTit">加入我们</div>
            <!--/标题-->
            <div class="conBase">
                {@foreach from=$list item=job@}
                <h4>{@$job.title@}</h4>
                <hr/>
                <p>{@$job.content@}</p>
                {@/foreach@}

            </div>
        </div>
        <div class="clearboth"></div>
    </div>
    <!--/内容-->
</div>
<!--mainContent end-->

<script type="text/javascript">
    $(function() {
        //顶部导航 选中状态
        $(".menu dd.m4 a").addClass("current")
    })
</script>

{@include 'footer.phtml'@}

