{@include 'header.phtml'@}

<!--mainContent start-->
<div class="mainContent">
    <!--内容-->
    <div class="content">
        <div class="contentTop">
            <!--标题-->
            <div class="pageTit">加入我们</div>
            <!--/标题-->
            <div class="conBase">
                {@foreach from=$list item=job@}
                <p><h5>{@$job.title@}</h5>
                <hr/>
                {@$job.content@}</p>
                {@/foreach@}

            </div>
        </div>
        <div class="clearboth"></div>
        <div class="contentBot"></div>
    </div>
    <!--/内容-->
</div>
<!--mainContent end-->


<!--copy start-->
<div class="footer">
    <div class="inner">
        <p class="txtC">24小时热线电话：13917605543</p>
        <p class="txtC">乐开音乐All Rights Reserved.</p>
        <p class="txtC"><a href="/job">招聘</a></p>
    </div>
</div>
<!--copy end-->

<script type="text/javascript">
    $(function() {
        //顶部导航 选中状态
        $(".menu dd.m4 a").addClass("current")
    })
</script>

{@include 'footer.phtml'@}

