<!--header-->
{@include 'header.phtml'@}
<!--/header-->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <!--menu-->
            {@include 'menu.phtml'@}
            <!--/menu-->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">新增案例明细-{@$case.name@}</h2>
            <div class="row placeholders">
                <a href="/admin/case/details/?id={@$case.id@}"><button class="btn btn-default">返回</button></a>
            </div>
            <div class="table-responsive">
                <form enctype="multipart/form-data" method="post" action="/admin/case/saveDetail">
                    <table class="table table-striped">
                        <tr>
                            <td>名称</td>
                            <td><input name="case_id" type="hidden" value="{@$case.id@}"/><input name="name"
                                                                                                 type="text"/></td>
                        </tr>
                        <tr>
                        <tr>
                            <td>排序</td>
                            <td><input name="order" type="text"/></td>
                        </tr>
                        <tr>
                            <td>标签</td>
                            <td><input name="lable" type="text"/></td>
                        </tr>
                        <tr>
                            <td>链接</td>
                            <td><input name="link" type="text"/></td>
                        </tr>
                        <tr>
                            <td>资源</td>
                            <td><input name="src[]" type="file"/></td>
                        </tr>
                        <tr>
                            <td colspan=2><input type="submit" value="提交"/> <input type="reset" value="重置"/></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

<!--footer-->
{@include 'footer.phtml'@}
<!--/footer-->
