<!--header-->
{@include 'header.phtml'@}
<!--/header-->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <!--menu-->
            {@include 'menu.phtml'@}
            <!--/menu-->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">案例中心</h2>
            <div class="row placeholders">
                <div class="col-xs-6 col-sm-3 placeholder">
                    <a href="/admin/case/addDetail/?id={@$case.id@}"><button class="btn btn-primary">增加案例明细</button></a>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <a href="/admin/case/index"><button class="btn btn-default">返回</button></a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>案例名称</th>
                        <th>名称</th>
                        <th>用户</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {@foreach from=$list item=detail@}
                    <tr>
                        <td>{@$detail.id@}</td>
                        <td>{@$case.name@}</td>
                        <td>{@$detail.name@}</td>
                        <td>{@$detail.order@}</td>
                        <td><a href="/admin/case/editDetail/?id={@$detail.id@}&case_id={@$case.id@}"><button class="btn btn-primary">修改</button></a>   <a
                                    href="/admin/case/delDetail/?id={@$detail.id@}&case_id={@$case.id@}"><button class="btn btn-danger">删除</button></a></td>
                    </tr>
                    {@/foreach@}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--footer-->
{@include 'footer.phtml'@}
<!--/footer-->