<!--header-->
{@include 'header.phtml'@}
<!--/header-->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <!--menu-->
            {@include 'menu.phtml'@}
            <!--/menu-->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">修改案例</h2>
            <div class="row placeholders">
                <h4><a href="/admin/case/index">返回</a></h4>
            </div>
            <div class="table-responsive">
                <form enctype="multipart/form-data" method="post" action="/admin/case/save">
                    <table class="table table-striped">
                        <tr>
                            <td>案例名称</td>
                            <td><input name="id" type="hidden" value="{@$case.id@}"/><input name="name" type="text"
                                                                                            value="{@$case.name@}"/>
                            </td>
                        </tr>
                        <tr>
                        <tr>
                            <td>案例类型</td>
                            <td><select name="type">
                                    {@foreach from=$caseCategory item=item@}
                                    <option value="{@$item.id@}" {@if $item.id eq $case.type@}selected{@
                                    /if@}>{@$item.name@}</option>
                                    {@/foreach@}
                                </select></td>
                        </tr>
                        <tr>
                            <td>排序</td>
                            <td><input name="order" type="text" value="{@$case.order@}"/></td>
                        </tr>
                        <tr>
                            <td>案例描述</td>
                            <td><textarea name="description"> {@$case.description@}</textarea></td>
                        </tr>
                        <tr>
                            <td>案例客户名称</td>
                            <td><input name="client" type="text" value="{@$case.client@}"/></td>
                        </tr>
                        <tr>
                            <td>案例标签</td>
                            <td><input name="lable" type="text" value="{@$case.lable@}"/></td>
                        </tr>
                        <tr>
                            <td>案例图标</td>
                            <td><input name="src[]" type="file""/>{@$case.icon@}</td>
                        </tr>
                        <tr>
                            <td>案例图片</td>
                            <td><input name="src[]" type="file"/>{@$case.img@}</td>
                        </tr>
                        <tr>
                            <td>案例视频</td>
                            <td><input name="src[]" type="file"/>{@$case.video@}</td>
                        </tr>
                        <tr>
                            <td colspan=2><input type="submit" value="提交"/> <input type="reset" value="重置"/></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

<!--footer-->
{@include 'footer.phtml'@}
<!--/footer-->
