<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<title>乐开音乐网</title>
<meta http-equiv="keywords" content="" />
<meta http-equiv="description" content="#" />
<link href="css/index.css" type="text/css" rel="stylesheet" />

</head>

<body>

<!--header start-->
<div class="header">
    <div class="inner">
        <!--logo-->
        <div class="logo fl"><a href="index.html" title="乐开音乐网">logo</a></div>
        
        <!--menu-->
        <div class="menu fr">
            <dl>
                <dd class="m1"><a href="index.html#banner">首页</a></dd>
                <dd class="m2"><a href="index.html#service">服务</a></dd>
                <dd class="m3"><a href="case.html">作品</a></dd>
                <dd class="m4"><a href="newsList.html">动态</a></dd>
                <dd class="m5"><a href="index.html#aboutUs">关于</a></dd>
                <dd class="m6"><a href="index.html#contact">联系</a></dd>
            </dl>
        </div>
        <!--/menu-->
        
        <div class="clearboth"></div>
    </div>
</div>
<!--header end-->