{@include 'header.phtml'@}

<!--音乐作品欣赏-->
<div class="case" id="case1">
	<div class="caseCon">
        <div class="caseTop">
        	<!--标题-->
            <h2>游戏配乐欣赏</h2>
            
            <!--轮播-->
            <div class="marqueeScroll" id="scroll01">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list1.list item=item@}
                        <li>
                        	<a href="Javascript:void(0)" onclick ="detail(this,1, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                    	{@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>   
            </div>
            <!--/轮播-->
            
            <!--播放-->
            <div class="casePlay">
            	<!--视频-->
                <div class="video fl">
                	<!--jplayer-->
                    <div id="jp_gui_video_1" class="jp-video jp-video-270p">
                        <div class="jp-type-single">
                            <div id="jplayer_video_1" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time"></div>
                                    <div class="jp-duration"></div>
                                    <div class="jp-title">
                                        <ul>
                                            <li>Big Buck Bunny Trailer</li>
                                        </ul>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <ul class="jp-controls">
                                            <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                                            <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                                            <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                                            <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                                            <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                                            <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                                        </ul>
                                        <div class="jp-volume-bar">
                                            <div class="jp-volume-bar-value"></div>
                                        </div>
                                        <ul class="jp-toggles">
                                            <li><a href="javascript:;" class="jp-full-screen" tabindex="1" title="full screen">full screen</a></li>
                                            <li><a href="javascript:;" class="jp-restore-screen" tabindex="1" title="restore screen">restore screen</a></li>
                                            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                                            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    
                	
                    <!--/jplayer-->
                </div>
                <!--/视频-->
                
                <!--详细信息-->
                <div class="caseInfro fr">
                	<div class="caseInfro_a">
                    	<p><span class="caseInfro_aTit">{@$list1.case.name@}</span><span class="caseInfro_aSty">{@$list1.case.lable@} {@$list1.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll"><span class="caseInfro_description">{@$list1.case.description@}</span></p>
                    </div>
                    <div class="line"></div>
                    
                    <div class="caseInfro_b">
                    	<dl>
                        	<dd>
                                <div class="caseInfro_bVideo">
                                 <!--jp音频-->
                                 <div id="jquery_jplayer_1" class="jp-jplayer"></div>
                                <div id="jp_container_1" class="jp-audio" role="application" aria-label="media player">
                                    <div class="jp-type-playlist">
                                        <div class="jp-gui jp-interface">
                                            <div class="jp-volume-controls">
                                                <button class="jp-mute" role="button" tabindex="0">mute</button>
                                                <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                                <div class="jp-volume-bar">
                                                  <div class="jp-volume-bar-value"></div>
                                              </div>
                                            </div>
                                            <div class="jp-controls-holder">
                                                <div class="jp-controls">
                                                    <button class="jp-previous" role="button" tabindex="0">previous</button>
                                                    <button class="jp-play" role="button" tabindex="0">play</button>
                                                    <button class="jp-stop" role="button" tabindex="0">stop</button>
                                                    <button class="jp-next" role="button" tabindex="0">next</button>
                                                </div>
                                                <div class="jp-progress">
                                                    <div class="jp-seek-bar">
                                                        <div class="jp-play-bar"></div>
                                                  </div>
                                              </div>
                                                <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                                <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                                <div class="jp-toggles">
                                                    <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                                    <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="jp-playlist">
                                            <ul>
                                                <li>&nbsp;</li>
                                            </ul>
                                        </div>
                                        <div class="jp-no-solution">
                                            <span>Update Required</span>
                                            To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                                        </div>
                                    </div>
                                </div>
                                <!--/jp音频-->
                                 
                                 
                                </div>
                            </dd>
                        </dl>
                    </div>
                </div>
                <!--/详细信息-->
                
            	<div class="clearboth"></div>
            </div>
            <!--/播放-->
            
                    
            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/音乐作品欣赏-->

<!--音效制作欣赏-->
<div class="case" id="case2">
	<div class="caseCon">
        <div class="caseTop">
        	<!--标题-->
            <h2>游戏音效欣赏</h2>
            
            <!--轮播-->
            <div class="marqueeScroll" id="scroll02">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list2.list item=item@}
                        <li>
                        	<a href="Javascript:void(0)" onclick ="detail(this,2, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                    	{@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>   
            </div>
            <!--/轮播-->
            
            <!--播放-->
            <div class="casePlay">
            	<!--视频-->
                <div class="video fl">
                	<!--jplayer-->
                    <div id="jp_gui_video_2" class="jp-video jp-video-270p">
                        <div class="jp-type-single">
                            <div id="jplayer_video_2" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time"></div>
                                    <div class="jp-duration"></div>
                                    <div class="jp-title">
                                        <ul>
                                            <li>Big Buck Bunny Trailer</li>
                                        </ul>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <ul class="jp-controls">
                                            <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                                            <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                                            <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                                            <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                                            <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                                            <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                                        </ul>
                                        <div class="jp-volume-bar">
                                            <div class="jp-volume-bar-value"></div>
                                        </div>
                                        <ul class="jp-toggles">
                                            <li><a href="javascript:;" class="jp-full-screen" tabindex="1" title="full screen">full screen</a></li>
                                            <li><a href="javascript:;" class="jp-restore-screen" tabindex="1" title="restore screen">restore screen</a></li>
                                            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                                            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    
                	
                    <!--/jplayer-->
                </div>
                <!--/视频-->
                
                <!--详细信息-->
                <div class="caseInfro fr">
                	<div class="caseInfro_a">
                    	<p><span class="caseInfro_aTit">{@$list2.case.name@}</span><span class="caseInfro_aSty">{@$list2.case.lable@} {@$list2.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll">{@$list2.case.description@}</p>
                    </div>
                    <div class="line"></div>
                    
                    <div class="caseInfro_b">
                    	<dl>
                        	<dd>
                                <div class="caseInfro_bVideo">
                                 <!--jp音频-->
                                 <div id="jquery_jplayer_2" class="jp-jplayer"></div>
                                <div id="jp_container_2" class="jp-audio" role="application" aria-label="media player">
                                    <div class="jp-type-playlist">
                                        <div class="jp-gui jp-interface">
                                            <div class="jp-volume-controls">
                                                <button class="jp-mute" role="button" tabindex="0">mute</button>
                                                <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                                <div class="jp-volume-bar">
                                                  <div class="jp-volume-bar-value"></div>
                                              </div>
                                            </div>
                                            <div class="jp-controls-holder">
                                                <div class="jp-controls">
                                                    <button class="jp-previous" role="button" tabindex="0">previous</button>
                                                    <button class="jp-play" role="button" tabindex="0">play</button>
                                                    <button class="jp-stop" role="button" tabindex="0">stop</button>
                                                    <button class="jp-next" role="button" tabindex="0">next</button>
                                                </div>
                                                <div class="jp-progress">
                                                    <div class="jp-seek-bar">
                                                        <div class="jp-play-bar"></div>
                                                  </div>
                                              </div>
                                                <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                                <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                                <div class="jp-toggles">
                                                    <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                                    <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="jp-playlist">
                                            <ul>
                                                <li>&nbsp;</li>
                                            </ul>
                                        </div>
                                        <div class="jp-no-solution">
                                            <span>Update Required</span>
                                            To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                                        </div>
                                    </div>
                                </div>
                                <!--/jp音频-->
                                 
                                 
                                </div>
                            </dd>
                        </dl>
                    </div>
                </div>
                <!--/详细信息-->
                
            	<div class="clearboth"></div>
            </div>
            <!--/播放-->
            
                    
            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/音效制作欣赏-->

<!--配音作品欣赏-->
<div class="case" id="case3">
	<div class="caseCon">
        <div class="caseTop">
        	<!--标题-->
            <h2>游戏配音欣赏</h2>
            
            <!--轮播-->
            <div class="marqueeScroll" id="scroll03">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list3.list item=item@}
                        <li>
                        	<a href="Javascript:void(0)" onclick ="detail(this,3, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                    	{@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>   
            </div>
            <!--/轮播-->
            
            <!--播放-->
            <div class="casePlay">
            	<!--视频-->
                <div class="video fl">
                	<!--jplayer-->
                    <div id="jp_gui_video_3" class="jp-video jp-video-270p">
                        <div class="jp-type-single">
                            <div id="jplayer_video_3" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time"></div>
                                    <div class="jp-duration"></div>
                                    <div class="jp-title">
                                        <ul>
                                            <li>Big Buck Bunny Trailer</li>
                                        </ul>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <ul class="jp-controls">
                                            <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                                            <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                                            <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                                            <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                                            <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                                            <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                                        </ul>
                                        <div class="jp-volume-bar">
                                            <div class="jp-volume-bar-value"></div>
                                        </div>
                                        <ul class="jp-toggles">
                                            <li><a href="javascript:;" class="jp-full-screen" tabindex="1" title="full screen">full screen</a></li>
                                            <li><a href="javascript:;" class="jp-restore-screen" tabindex="1" title="restore screen">restore screen</a></li>
                                            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                                            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    
                	
                    <!--/jplayer-->
                </div>
                <!--/视频-->
                
                <!--详细信息-->
                <div class="caseInfro fr">
                	<div class="caseInfro_a">
                    	<p><span class="caseInfro_aTit">{@$list3.case.name@}</span><span class="caseInfro_aSty">{@$list3.case.lable@} {@$list3.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll">{@$list3.case.description@}</p>
                    </div>
                    <div class="line"></div>
                    
                    <div class="caseInfro_b">
                    	<dl>
                        	<dd>
                                <div class="caseInfro_bVideo">
                                 <!--jp音频-->
                                 <div id="jquery_jplayer_3" class="jp-jplayer"></div>
                                <div id="jp_container_3" class="jp-audio" role="application" aria-label="media player">
                                    <div class="jp-type-playlist">
                                        <div class="jp-gui jp-interface">
                                            <div class="jp-volume-controls">
                                                <button class="jp-mute" role="button" tabindex="0">mute</button>
                                                <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                                <div class="jp-volume-bar">
                                                  <div class="jp-volume-bar-value"></div>
                                              </div>
                                            </div>
                                            <div class="jp-controls-holder">
                                                <div class="jp-controls">
                                                    <button class="jp-previous" role="button" tabindex="0">previous</button>
                                                    <button class="jp-play" role="button" tabindex="0">play</button>
                                                    <button class="jp-stop" role="button" tabindex="0">stop</button>
                                                    <button class="jp-next" role="button" tabindex="0">next</button>
                                                </div>
                                                <div class="jp-progress">
                                                    <div class="jp-seek-bar">
                                                        <div class="jp-play-bar"></div>
                                                  </div>
                                              </div>
                                                <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                                <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                                <div class="jp-toggles">
                                                    <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                                    <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="jp-playlist">
                                            <ul>
                                                <li>&nbsp;</li>
                                            </ul>
                                        </div>
                                        <div class="jp-no-solution">
                                            <span>Update Required</span>
                                            To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                                        </div>
                                    </div>
                                </div>
                                <!--/jp音频-->
                                 
                                 
                                </div>
                            </dd>
                        </dl>
                    </div>
                </div>
                <!--/详细信息-->
                
            	<div class="clearboth"></div>
            </div>
            <!--/播放-->
            
                    
            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/配音作品欣赏-->

<!--CG视频欣赏-->
<div class="case" id="case4">
	<div class="caseCon">
        <div class="caseTop">
        	<!--标题-->
            <h2>CG视频欣赏</h2>
            
            <!--轮播-->
            <div class="marqueeScroll" id="scroll04">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list4.list item=item@}
                        <li>
                        	<a href="Javascript:void(0)" onclick ="detail(this,4, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                    	{@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>   
            </div>
            <!--/轮播-->
            
            <!--播放-->
            <div class="casePlay">
            	<!--视频-->
                <div class="video fl">
                	<!--jplayer-->
                    <div id="jp_gui_video_4" class="jp-video jp-video-270p">
                        <div class="jp-type-single">
                            <div id="jplayer_video_4" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time"></div>
                                    <div class="jp-duration"></div>
                                    <div class="jp-title">
                                        <ul>
                                            <li>Big Buck Bunny Trailer</li>
                                        </ul>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <ul class="jp-controls">
                                            <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                                            <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                                            <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                                            <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                                            <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                                            <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                                        </ul>
                                        <div class="jp-volume-bar">
                                            <div class="jp-volume-bar-value"></div>
                                        </div>
                                        <ul class="jp-toggles">
                                            <li><a href="javascript:;" class="jp-full-screen" tabindex="1" title="full screen">full screen</a></li>
                                            <li><a href="javascript:;" class="jp-restore-screen" tabindex="1" title="restore screen">restore screen</a></li>
                                            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                                            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    
                	
                    <!--/jplayer-->
                </div>
                <!--/视频-->
                
                <!--详细信息-->
                <div class="caseInfro fr">
                	<div class="caseInfro_a">
                    	<p><span class="caseInfro_aTit">{@$list4.case.name@}</span><span class="caseInfro_aSty">{@$list4.case.lable@} {@$list4.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll">{@$list4.case.description@}</p>
                    </div>
                    <div class="line"></div>
                    
                    <div class="caseInfro_b">
                    	<dl>
                        	<dd>
                                <div class="caseInfro_bVideo">
                                 <!--jp音频-->
                                 <div id="jquery_jplayer_4" class="jp-jplayer"></div>
                                <div id="jp_container_4" class="jp-audio" role="application" aria-label="media player">
                                    <div class="jp-type-playlist">
                                        <div class="jp-gui jp-interface">
                                            <div class="jp-volume-controls">
                                                <button class="jp-mute" role="button" tabindex="0">mute</button>
                                                <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                                <div class="jp-volume-bar">
                                                  <div class="jp-volume-bar-value"></div>
                                              </div>
                                            </div>
                                            <div class="jp-controls-holder">
                                                <div class="jp-controls">
                                                    <button class="jp-previous" role="button" tabindex="0">previous</button>
                                                    <button class="jp-play" role="button" tabindex="0">play</button>
                                                    <button class="jp-stop" role="button" tabindex="0">stop</button>
                                                    <button class="jp-next" role="button" tabindex="0">next</button>
                                                </div>
                                                <div class="jp-progress">
                                                    <div class="jp-seek-bar">
                                                        <div class="jp-play-bar"></div>
                                                  </div>
                                              </div>
                                                <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                                <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                                <div class="jp-toggles">
                                                    <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                                    <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="jp-playlist">
                                            <ul>
                                                <li>&nbsp;</li>
                                            </ul>
                                        </div>
                                        <div class="jp-no-solution">
                                            <span>Update Required</span>
                                            To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                                        </div>
                                    </div>
                                </div>
                                <!--/jp音频-->
                                 
                                 
                                </div>
                            </dd>
                        </dl>
                    </div>
                </div>
                <!--/详细信息-->
                
            	<div class="clearboth"></div>
            </div>
            <!--/播放-->
            
                    
            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/CG视频欣赏-->

<!--影视动漫欣赏-->
<div class="case" id="case5">
	<div class="caseCon">
        <div class="caseTop">
        	<!--标题-->
            <h2>影视动漫</h2>
            
            <!--轮播-->
            <div class="marqueeScroll" id="scroll05">
                <!--控制按钮 start-->
                <div class="marqueeScroll_control_left"><a href="javascript:void(0)">左箭头</a></div>
                <div class="marqueeScroll_control_right"><a href="javascript:void(0)">右箭头</a></div>
                <!--控制按钮 end-->
                <div class="marqueeScroll_con">
                    <ul>
                        {@foreach from=$list5.list item=item@}
                        <li>
                        	<a href="Javascript:void(0)" onclick ="detail(this,5, {@$item.id@});" id='{@$item.id@}'><img src="{@$item.icon@}" width="106" height="106" /><i></i></a>
                            <p class="txtC">{@$item.name@}<br>{@$item.client@}</p>
                        </li>
                    	{@/foreach@}
                    </ul>
                </div>
                <div class="clearboth"></div>   
            </div>
            <!--/轮播-->
            
            <!--播放-->
            <div class="casePlay">
            	<!--视频-->
                <div class="video fl">
                	<!--jplayer-->
                    
                    <div id="jp_gui_video_5" class="jp-video jp-video-270p">
                        <div class="jp-type-single">
                            <div id="jplayer_video_5" class="jp-jplayer"></div>
                            <div class="jp-gui">
                                <div class="jp-video-play">
                                    <a href="javascript:;" class="jp-video-play-icon" tabindex="1">play</a>
                                </div>
                                <div class="jp-interface">
                                    <div class="jp-progress">
                                        <div class="jp-seek-bar">
                                            <div class="jp-play-bar"></div>
                                        </div>
                                    </div>
                                    <div class="jp-current-time"></div>
                                    <div class="jp-duration"></div>
                                    <div class="jp-title">
                                        <ul>
                                            <li>Big Buck Bunny Trailer</li>
                                        </ul>
                                    </div>
                                    <div class="jp-controls-holder">
                                        <ul class="jp-controls">
                                            <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                                            <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                                            <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                                            <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                                            <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                                            <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                                        </ul>
                                        <div class="jp-volume-bar">
                                            <div class="jp-volume-bar-value"></div>
                                        </div>
                                        <ul class="jp-toggles">
                                            <li><a href="javascript:;" class="jp-full-screen" tabindex="1" title="full screen">full screen</a></li>
                                            <li><a href="javascript:;" class="jp-restore-screen" tabindex="1" title="restore screen">restore screen</a></li>
                                            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                                            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="jp-no-solution">
                                <span>Update Required</span>
                                To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                            </div>
                        </div>
                    </div>
                    
                	
                    <!--/jplayer-->
                </div>
                <!--/视频-->
                
                <!--详细信息-->
                <div class="caseInfro fr">
                	<div class="caseInfro_a">
                    	<p><span class="caseInfro_aTit">{@$list5.case.name@}</span><span class="caseInfro_aSty">{@$list5.case.lable@} {@$list5.case.client@}</span> </p>
                        <p style="height:35px;overflow-y:scroll">{@$list5.case.description@}</p>
                    </div>
                    <div class="line"></div>
                    
                    <div class="caseInfro_b">
                    	<dl>
                        	<dd>
                                <div class="caseInfro_bVideo">
                                 <!--jp音频-->
                                 <div id="jquery_jplayer_5" class="jp-jplayer"></div>
                                <div id="jp_container_5" class="jp-audio" role="application" aria-label="media player">
                                    <div class="jp-type-playlist">
                                        <div class="jp-gui jp-interface">
                                            <div class="jp-volume-controls">
                                                <button class="jp-mute" role="button" tabindex="0">mute</button>
                                                <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
                                                <div class="jp-volume-bar">
                                                  <div class="jp-volume-bar-value"></div>
                                              </div>
                                            </div>
                                            <div class="jp-controls-holder">
                                                <div class="jp-controls">
                                                    <button class="jp-previous" role="button" tabindex="0">previous</button>
                                                    <button class="jp-play" role="button" tabindex="0">play</button>
                                                    <button class="jp-stop" role="button" tabindex="0">stop</button>
                                                    <button class="jp-next" role="button" tabindex="0">next</button>
                                                </div>
                                                <div class="jp-progress">
                                                    <div class="jp-seek-bar">
                                                        <div class="jp-play-bar"></div>
                                                  </div>
                                              </div>
                                                <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
                                                <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
                                                <div class="jp-toggles">
                                                    <button class="jp-repeat" role="button" tabindex="0">repeat</button>
                                                    <button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="jp-playlist">
                                            <ul>
                                                <li>&nbsp;</li>
                                            </ul>
                                        </div>
                                        <div class="jp-no-solution">
                                            <span>Update Required</span>
                                            To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                                        </div>
                                    </div>
                                </div>
                                <!--/jp音频-->
                                 
                                 
                                </div>
                            </dd>
                        </dl>
                    </div>
                </div>
                <!--/详细信息-->
                
            	<div class="clearboth"></div>
            </div>
            <!--/播放-->
            
                    
            <div class="clearboth"></div>
        </div>
        <div class="caseBot"></div>
    </div>
</div>
<!--/影视动漫欣赏-->

<!--[if lte IE 6]>
<script src="js/iepng.js" type="text/javascript"></script>
<script>
DD_belatedPNG.fix('*');
</script>
<![endif]-->
<script type="text/javascript">
//$(function() {  
//	//顶部导航 选中状态
//	$(".menu dd.m3 a").addClass("current")
//})
</script>
	<script type="text/javascript" src="http://192.168.1.200/js/jquery1.4.2.min.js"></script>
	<script type="text/javascript" src="http://192.168.1.200/js/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="http://192.168.1.200/js/allOneScroll.js"></script>
	<script type="text/javascript" src="http://192.168.1.200/jplayer/jquery.jplayer.min.js"></script>
	<script type="text/javascript" src="http://192.168.1.200/jplayer/jplayer.playlist.min.js"></script>
	<script type="text/javascript" src="http://192.168.1.200/js/case.js"></script>
	
{@include 'footer.phtml'@}
