{@include 'header.phtml'@}

<div class="margin_head"  style="background-color:#e7efef;">
    <img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.banner@}">
</div>

<h3 class="text-center lineHeight">用音乐开启孩子的时代审美</h3>

<div class="container">
    <div class="row" style="padding: 20px;">
        <div class="col-12">
            <ul id="myTab" class="nav nav-pills nav-justified">
                {@foreach from=$list item=course@}
                <li class="nav-item" style="margin: 5px;">
                    <a href="#tab{@$course.id@}" data-toggle="tab"><button type="button" class="btn btn-info">{@$course.name@}</button></a>
                </li>
                {@/foreach@}
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <div id="myTabContent" class="tab-content">
        {@foreach from=$list item=course@}
        <div class="tab-pane fade" id="tab{@$course.id@}">
            <div class="row">
                <div class="col-md-6">
                    <h4 class="lineHeight">{@$course.name@}</h4>
                    <p class="lineHeight1">{@$course.description@}</p>
                    <h4 class="lineHeight">{@$course.title_1@}</h4>
                    <p class="lineHeight1">{@$course.content_1@}</p>
                    <h4 class="lineHeight">{@$course.title_2@}</h4>
                    <p class="lineHeight1">{@$course.content_2@}</p>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="carousel-inner img-responsive"
                                 src="http://{@$config.host@}/{@$course.media@}">
                        </div>
                    </div>
                    <div class="row text-center" style="padding:50px 0;">
                        {@if $course.labels@}
                        {@foreach from=$course.labels item=label@}
                        <div class="col-3">
                            <div style="color:white;background-color: #5bc0de;border-radius: 50%;width: 77px;height: 77px;">
                                <span class="center-vertical">{@$label@}</span>
                            </div>
                        </div>
                        {@/foreach@}
                        {@/if@}
                    </div>
                </div>
            </div>
        </div>
        {@/foreach@}
    </div>
</div>
{@include 'footer.phtml'@}

<script>
  $(function () {
    $('#myTab li:eq(0) a').tab('show');
  });
</script>