<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://{@$config['host']@}/js/jquery.min.js"></script>
<script src="http://{@$config['host']@}/bootstrap-3.3.7/js/bootstrap.min.js"></script>
<script src="http://{@$config['host']@}/js/docs.min.js"></script>
<script src="http://{@$config['host']@}/js/jquery.form.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://{@$config['host']@}/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>