<ul class="nav nav-sidebar">
    <li class="active"><a href="/admin/index/main">首页 <span class="sr-only">(current)</span></a></li>
    <li><a href="/admin/case/index">案例中心</a></li>
    <li><a href="/admin/news/index">新闻中心</a></li>
    <li><a href="/admin/photo/index">图片中心</a></li>
    <li><a href="/admin/job/index">招聘中心</a></li>
    <li><a href="/admin/index/admin">管理帐号</a></li>
    <li><a href="/admin/index/out">退出</a></li>
</ul>