<ul class="nav nav-sidebar">
    <li><a href="/admin/index/main">首页</a></li>
    <li><a href="/admin/case/index">案例中心</a></li>
    <li><a href="/admin/news/index">新闻中心</a></li>
    <li><a href="/admin/photo/index">图片中心</a></li>
    <li><a href="/admin/job/index">招聘中心</a></li>
    <li><a href="/admin/config/index">网站配置</a></li>
    <li><a href="/admin/config/index/?page=2">首页配置</a></li>
    <li><a href="/admin/config/index/?page=3">课程页配置</a></li>
    <li><a href="/admin/config/index/?page=4">活动页配置</a></li>
    <li><a href="/admin/config/index/?page=5">分享页配置</a></li>
    <li><a href="/admin/config/index/?page=6">介绍页配置</a></li>
    <li><a href="/admin/index/admin">管理帐号</a></li>
    <li><a href="/admin/index/out">退出</a></li>
</ul>