{@include 'header.phtml'@}

<!--轮播 start-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="margin-top: 95px;">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img1@}" alt="1">
            <div class="carousel-caption d-none d-md-block" style="bottom: 150px;">
                <h1>{@$pageConfig.carousel_img1_title@}</h1>
                <p></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img1@}" alt="2">
            <div class="carousel-caption d-none d-md-block" style="bottom: 150px;">
                <h1>{@$pageConfig.carousel_img2_title@}</h1>
                <p></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img3@}" alt="3">
            <div class="carousel-caption d-none d-md-block" style="bottom: 150px;">
                <h1>{@$pageConfig.carousel_img3_title@}</h1>
                <p></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img4@}" alt="4">
            <div class="carousel-caption d-none d-md-block" style="bottom: 150px;">
                <h1>{@$pageConfig.carousel_img4_title@}</h1>
                <p></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img5@}" alt="5">
            <div class="carousel-caption d-none d-md-block" style="bottom: 150px;">
                <h1>{@$pageConfig.carousel_img5_title@}</h1>
                <p></p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!--轮播 end-->
<div class="container">
    <!--part1 start-->
    <div class="row">
        <div class="col-md-6" style="padding: 0;">
            <h1 style="line-height: 300%;">{@$pageConfig.title1@}</h1>
            <p style="line-height: 200%;padding: 10px">{@$pageConfig.description1@}</p>
            <h1 style="line-height: 300%;">{@$pageConfig.title2@}</h1>
            <p style="line-height: 200%;padding: 10px">{@$pageConfig.description2@}</p>
            <img class="carousel-inner img-responsive" style="width: 100%;margin-top: 13px;"
                 src="./images/index/a.jpg"/>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6" style="padding: 0;">
                    <div class="musicDescription" style="background-color: #6fad6d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">音乐启蒙<br/>0-3岁</span>
                    </div>
                    <img class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.cause1@}"/>
                </div>
                <div class="col-md-6" style="padding: 0;">
                    <div class="musicDescription" style="background-color: #ada36d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">音乐素养<br/>3-6岁</span>
                    </div>
                    <img class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.cause2@}"/>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6" style="padding: 0;">
                    <div class="musicDescription" style="background-color: #ad806d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">乐器学习<br/>5-12岁</span>
                    </div>
                    <img class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.cause3@}"/>
                </div>
                <div class="col-md-6" style="padding: 0;">
                    <div class="musicDescription" style="background-color: #6e6dad">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">乐队表演</span>
                    </div>
                    <img class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.cause4@}"/>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6" style="padding: 0;">
                    <div class="musicDescription" style="background-color: #ada36d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">儿童合唱团</span>
                    </div>
                    <img class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.cause5@}"/>
                </div>
                <div class="col-md-6" style="padding: 0;">
                    <div class="musicDescription" style="background-color: #6fad6d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">家庭亲子乐队</span>
                    </div>
                    <img class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.cause6@}"/>
                </div>
            </div>
        </div>
    </div>
    <!--part1 end-->

    <!--part2 start-->
    <div class="row" style="margin-top: 80px">
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-xs-2"><img class="carousel-inner img-responsive" src="./images/index/1.png"/></div>
                <div class="col-md-10 col-xs-10">
                    <h4 style="line-height: 200%;font-weight:bold">{@$pageConfig.cause_title1@}</h4>
                    <p style="line-height: 200%">{@$pageConfig.cause_description1@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-xs-2"><img class="carousel-inner img-responsive" src="./images/index/2.png"/></div>
                <div class="col-md-10 col-xs-10">
                    <h4 style="line-height: 200%;font-weight:bold">{@$pageConfig.cause_title2@}</h4>
                    <p style="line-height: 200%">{@$pageConfig.cause_description2@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-xs-2"><img class="carousel-inner img-responsive" src="./images/index/3.png"/></div>
                <div class="col-md-10 col-xs-10">
                    <h4 style="line-height: 200%;font-weight:bold">{@$pageConfig.cause_title3@}</h4>
                    <p style="line-height: 200%">{@$pageConfig.cause_description3@}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top: 80px">
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-xs-2"><img class="carousel-inner img-responsive" src="./images/index/4.png"/></div>
                <div class="col-md-10 col-xs-10">
                    <h4 style="line-height: 200%;font-weight:bold">{@$pageConfig.cause_title4@}</h4>
                    <p style="line-height: 200%">{@$pageConfig.cause_description4@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-xs-2"><img class="carousel-inner img-responsive" src="./images/index/5.png"/></div>
                <div class="col-md-10 col-xs-10">
                    <h4 style="line-height: 200%;font-weight:bold">{@$pageConfig.cause_title5@}</h4>
                    <p style="line-height: 200%">{@$pageConfig.cause_description5@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-xs-2"><img class="carousel-inner img-responsive" src="./images/index/6.png"/></div>
                <div class="col-md-10">
                    <h4 style="line-height: 200%;font-weight:bold">{@$pageConfig.cause_title6@}</h4>
                    <p style="line-height: 200%">{@$pageConfig.cause_description6@}</p>
                </div>
            </div>
        </div>
    </div>
    <!--part2 end-->
</div>
<!--banner start-->
<div style="background-color: #4f4f4f;margin-top: 80px">
    <div class="container">
        <div class="row" style="padding: 10px;">
            <div class="col-md-6 text-center"><h1 style="line-height: 300%;color: white;font-weight:bold">匠心打造</h1>
            </div>
            <div class="col-md-6 text-center" style="padding: 20px"><img src="./img/qr.png" width="100px"
                                                                         height="100px"></div>
        </div>
    </div>
</div>
<!--banner end-->

<!--part3 start-->
<div class="container">
    <div class="row">
        <div class="col-md-6" style="padding: 0"><img class="carousel-inner img-responsive" src="./images/index/c.jpg"/>
        </div>
        <div class="col-md-6" style="padding-left: 40px;padding-right:40px;background-color: #f2f2ea">
            <h1 style="line-height: 150%">{@$pageConfig.title3@}</h1>
            <p style="line-height: 200%">{@$pageConfig.description3@}</p>
            <h1 style="line-height: 150%">{@$pageConfig.title4@}</h1>
            <p style="line-height: 200%">{@$pageConfig.description4@}</p>
            <h1 style="line-height: 150%">{@$pageConfig.title5@}</h1>
            <p style="line-height: 200%">{@$pageConfig.description5@}</p>
        </div>
    </div>
</div>

{@include 'footer.phtml'@}
