{@include 'header.phtml'@}

<!--轮播 start-->
<div id="carouselExampleIndicators" class="carousel slide margin_head" data-ride="carousel" >
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img1@}" alt="1">
            <div class="carousel-caption d-none d-md-block" style="top: 50%;">
                <h1>{@$pageConfig.carousel_img1_title@}</h1>
                <p></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img2@}" alt="2">
            <div class="carousel-caption d-none d-md-block" style="top: 50%;">
                <h1>{@$pageConfig.carousel_img2_title@}</h1>
                <p></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img3@}" alt="3">
            <div class="carousel-caption d-none d-md-block" style="top: 50%;">
                <h1>{@$pageConfig.carousel_img3_title@}</h1>
                <p></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img4@}" alt="4">
            <div class="carousel-caption d-none d-md-block" style="top: 50%;">
                <h1>{@$pageConfig.carousel_img4_title@}</h1>
                <p></p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{@$pageConfig.carousel_img5@}" alt="5">
            <div class="carousel-caption d-none d-md-block" style="top: 50%;">
                <h1>{@$pageConfig.carousel_img5_title@}</h1>
                <p></p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!--轮播 end-->
<div class="container">
    <!--part1 start-->
    <div class="row">
        <div class="col-md-6" style="padding: 0;">
            <h1 class="lineHeight">{@$pageConfig.title1@}</h1>
            <p class="lineHeight1" style="padding: 10px">{@$pageConfig.description1@}</p>
            <h1 class="lineHeight">{@$pageConfig.title2@}</h1>
            <p class="lineHeight1" style="padding: 10px">{@$pageConfig.description2@}</p>
            <img class="carousel-inner img-responsive" style="width: 100%;margin-top:10px"
                 src="{@$pageConfig.description1_img@}"/>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-6" style="padding: 0;cursor: pointer;">
                    <div id="courseDesc1" class="musicDescription" style="background-color: #6fad6d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">{@$pageConfig.course1_title@}<br/>{@$pageConfig.course1_description@}</span>
                    </div>
                        <img id="courseImg1" class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.course1@}"/>
                </div>
                <div class="col-6" style="padding: 0;cursor: pointer;">
                    <div id="courseDesc2" class="musicDescription" style="background-color: #ada36d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">{@$pageConfig.course2_title@}<br/>{@$pageConfig.course2_description@}</span>
                    </div>
                    <img id="courseImg2" class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.course2@}"/>
                </div>
            </div>
            <div class="row">
                <div class="col-6" style="padding: 0;cursor: pointer;">
                    <div id="courseDesc3" class="musicDescription" style="background-color: #ad806d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">{@$pageConfig.course3_title@}<br/>{@$pageConfig.course3_description@}</span>
                    </div>
                    <img id="courseImg3" class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.course3@}"/>
                </div>
                <div class="col-6" style="padding: 0;cursor: pointer;">
                    <div id="courseDesc4" class="musicDescription" style="background-color: #6e6dad">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">{@$pageConfig.course4_title@}<br/>{@$pageConfig.course4_description@}</span>
                    </div>
                    <img id="courseImg4" class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.course4@}"/>
                </div>
            </div>
            <div class="row">
                <div class="col-6" style="padding: 0;cursor: pointer;">
                    <div id="courseDesc5" class="musicDescription" style="background-color: #ada36d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">{@$pageConfig.course5_title@}<br/>{@$pageConfig.course5_description@}</span>
                    </div>
                    <img id="courseImg5" class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.course5@}"/>
                </div>
                <div class="col-6" style="padding: 0;cursor: pointer;">
                    <div id="courseDesc6" class="musicDescription" style="background-color: #6fad6d">
                        <span class="center-vertical" style="padding: 20px;border-top: 1px solid white;border-bottom: 1px solid white;">{@$pageConfig.course6_title@}<br/>{@$pageConfig.course6_description@}</span>
                    </div>
                    <img id="courseImg6" class="carousel-inner img-responsive musicImg6" src="{@$pageConfig.course6@}"/>
                </div>
            </div>
        </div>
    </div>
    <!--part1 end-->

    <!--part2 start-->
    <div class="row marginTop">
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-2"><img class="carousel-inner img-responsive" src="./images/index/1.png"/></div>
                <div class="col-md-10 col-10">
                    <h4 class="lineHeight1" style="font-weight:bold">{@$pageConfig.course_title1@}</h4>
                    <p class="lineHeight1">{@$pageConfig.course_description1@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-2"><img class="carousel-inner img-responsive" src="./images/index/2.png"/></div>
                <div class="col-md-10 col-10">
                    <h4 class="lineHeight1" style="font-weight:bold">{@$pageConfig.course_title2@}</h4>
                    <p class="lineHeight1">{@$pageConfig.course_description2@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-2"><img class="carousel-inner img-responsive" src="./images/index/3.png"/></div>
                <div class="col-md-10 col-10">
                    <h4 class="lineHeight1" style="font-weight:bold">{@$pageConfig.course_title3@}</h4>
                    <p class="lineHeight1">{@$pageConfig.course_description3@}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row marginTop">
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-2"><img class="carousel-inner img-responsive" src="./images/index/4.png"/></div>
                <div class="col-md-10 col-10">
                    <h4 class="lineHeight1" style="font-weight:bold">{@$pageConfig.course_title4@}</h4>
                    <p class="lineHeight1">{@$pageConfig.course_description4@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-2"><img class="carousel-inner img-responsive" src="./images/index/5.png"/></div>
                <div class="col-md-10 col-10">
                    <h4 class="lineHeight1" style="font-weight:bold">{@$pageConfig.course_title5@}</h4>
                    <p class="lineHeight1">{@$pageConfig.course_description5@}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-2 col-2"><img class="carousel-inner img-responsive" src="./images/index/6.png"/></div>
                <div class="col-md-10 col-10">
                    <h4 class="lineHeight1" style="font-weight:bold">{@$pageConfig.course_title6@}</h4>
                    <p class="lineHeight1">{@$pageConfig.course_description6@}</p>
                </div>
            </div>
        </div>
    </div>
    <!--part2 end-->
</div>
<!--banner start-->
<div class="marginTop" style="background-color: #4f4f4f;">
    <div class="container">
        <div class="row" style="padding: 10px;">
            <div class="col-md-6 col-7 text-center"><h1 style="line-height: 300%;color: white;font-weight:bold">匠心打造</h1>
            </div>
            <div class="col-md-6 col-5 text-center" style="padding: 20px"><img src="./img/qr.png" width="100px"
                                                                         height="100px"></div>
        </div>
    </div>
</div>
<!--banner end-->

<!--part3 start-->
<div class="container">
    <div class="row">
        <div class="col-md-6" style="padding: 0"><img class="carousel-inner img-responsive" src="{@$pageConfig.description2_img@}"/>
        </div>
        <div class="col-md-6 padding1" style="background-color: #f2f2ea">
            <h1 style="line-height: 150%">{@$pageConfig.title3@}</h1>
            <p class="lineHeight1">{@$pageConfig.description3@}</p>
            <h1 style="line-height: 150%">{@$pageConfig.title4@}</h1>
            <p class="lineHeight1">{@$pageConfig.description4@}</p>
            <h1 style="line-height: 150%">{@$pageConfig.title5@}</h1>
            <p class="lineHeight1">{@$pageConfig.description5@}</p>
        </div>
    </div>
</div>

{@include 'footer.phtml'@}

<script>
  var block_1_1 = document.getElementById('courseImg1');
  var block_1_2 = document.getElementById('courseDesc1');
  var block_2_1 = document.getElementById('courseImg2');
  var block_2_2 = document.getElementById('courseDesc2');
  var block_3_1 = document.getElementById('courseImg3');
  var block_3_2 = document.getElementById('courseDesc3');
  var block_4_1 = document.getElementById('courseImg4');
  var block_4_2 = document.getElementById('courseDesc4');
  var block_5_1 = document.getElementById('courseImg5');
  var block_5_2 = document.getElementById('courseDesc5');
  var block_6_1 = document.getElementById('courseImg6');
  var block_6_2 = document.getElementById('courseDesc6');

  block_1_1.onmouseover = function () {
    block_1_1.style.display = 'none';
    block_1_2.style.display = 'block';
  }
  block_1_2.onmouseout = function () {
    block_1_1.style.display = 'block';
    block_2_1.style.display = 'block';
    block_3_1.style.display = 'block';
    block_4_1.style.display = 'block';
    block_5_1.style.display = 'block';
    block_6_1.style.display = 'block';
    block_1_2.style.display = 'none';
  }

  block_2_1.onmouseover = function () {
    block_2_1.style.display = 'none';
    block_2_2.style.display = 'block';
  }
  block_2_2.onmouseout = function () {
    block_1_1.style.display = 'block';
    block_2_1.style.display = 'block';
    block_3_1.style.display = 'block';
    block_4_1.style.display = 'block';
    block_5_1.style.display = 'block';
    block_6_1.style.display = 'block';
    block_2_2.style.display = 'none';
  }

  block_3_1.onmouseover = function () {
    block_3_1.style.display = 'none';
    block_3_2.style.display = 'block';
  }
  block_3_2.onmouseout = function () {
    block_1_1.style.display = 'block';
    block_2_1.style.display = 'block';
    block_3_1.style.display = 'block';
    block_4_1.style.display = 'block';
    block_5_1.style.display = 'block';
    block_6_1.style.display = 'block';
    block_3_2.style.display = 'none';
  }

  block_4_1.onmouseover = function () {
    block_4_1.style.display = 'none';
    block_4_2.style.display = 'block';
  }
  block_4_2.onmouseout = function () {
    block_1_1.style.display = 'block';
    block_2_1.style.display = 'block';
    block_3_1.style.display = 'block';
    block_4_1.style.display = 'block';
    block_5_1.style.display = 'block';
    block_6_1.style.display = 'block';
    block_4_2.style.display = 'none';
  }

  block_5_1.onmouseover = function () {
    block_5_1.style.display = 'none';
    block_5_2.style.display = 'block';
  }
  block_5_2.onmouseout = function () {
    block_1_1.style.display = 'block';
    block_2_1.style.display = 'block';
    block_3_1.style.display = 'block';
    block_4_1.style.display = 'block';
    block_5_1.style.display = 'block';
    block_6_1.style.display = 'block';
    block_5_2.style.display = 'none';
  }

  block_6_1.onmouseover = function () {
    block_6_1.style.display = 'none';
    block_6_2.style.display = 'block';
  }
  block_6_2.onmouseout = function () {
    block_1_1.style.display = 'block';
    block_2_1.style.display = 'block';
    block_3_1.style.display = 'block';
    block_4_1.style.display = 'block';
    block_5_1.style.display = 'block';
    block_6_1.style.display = 'block';
    block_6_2.style.display = 'none';
  }

</script>
