<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge，chrome=1">
    <title>乐开儿童音乐王国|中国最权威的儿童音乐教育品牌</title>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
    <link rel="stylesheet" href="./css/bootstrap.css">
    <link rel="stylesheet" href="./css/newstyle.css">
    <link rel="stylesheet" href="./jplayer/index/jplayer.css" media="all"/>
    <script src="./js/jquery-3.2.1.min.js"></script>
    <script src="./js/bootstrap.js"></script>

</head>
<body>
    <!--head start-->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid" style="background-color:#242629">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">导航</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span style="display: block;padding:0 0 0 20px;">
                    <img src="./img/logosmall.png" width="50px">
                    <a class="" href="/" style="color: white;font-size: x-large;line-height:70px">乐开儿童音乐王国</a>
                </span>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/" style="color: white;">首页</a></li>
                    <li><a href="/case" style="color: white;">乐开作品</a></li>
                    <li><a href="/photo" style="color: white;">乐开风采</a></li>
                    <li><a href="/news" style="color: white;">乐开文化</a></li>
                    <li><a href="/job" style="color: white;">加入乐开</a></li>
                </ul>
            </div>
        </div>
        <div class="header-wrapper"></div>
    </nav>
    <!--head end-->
    <!--轮播 start-->
    <div style="position:relative;">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- 轮播（Carousel）指标 -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
                <li data-target="#myCarousel" data-slide-to="4"></li>
            </ol>
            <!-- 轮播（Carousel）项目 -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="{@$config.carousel_img1@}" alt="Third slide">
                </div>
                <div class="item">
                    <img src="{@$config.carousel_img2@}" alt="First slide">
                </div>
                <div class="item">
                    <img src="{@$config.carousel_img3@}" alt="Second slide">
                </div>
                <div class="item">
                    <img src="{@$config.carousel_img4@}" alt="Third slide">
                </div>
                <div class="item">
                    <img src="{@$config.carousel_img5@}" alt="Third slide">
                </div>
            </div>
            <!-- 轮播（Carousel）导航 -->
            <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
        </div>
        <div class="videoTop">
            <div class="play-video-btn">
                <a data-toggle="modal" data-target="#videoModal"oncli>
                    <img src="./img/play-video-btn.png" alt="Play Video" width="70px" height="70ox">
                </a>
            </div>
        </div>
    </div>
    <!--轮播 end-->
    <!--标签页 start-->
    <div style="background-color: #a32b2d">
        <div class="container">
            <ul id="myTab" class="nav nav-pills col-md-offset-4">
                <li class="active">
                    <a href="#music" data-toggle="tab">乐开音乐</a>
                </li>
                <li>
                    <a href="#teacher" data-toggle="tab">乐开师训</a>
                </li>
                <li>
                    <a href="#activity" data-toggle="tab">乐开风采</a>
                </li>
                <li>
                    <a href="#about" data-toggle="tab">关于乐开</a>
                </li>
            </ul>
        </div>
    </div>
    <div style="background-color: #eee">
        <div class="container">
            <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade in active" id="music">
                    <div class="container paddingrow">
                        <div class="row">
                            <div class="col-md-2 col-md-offset-1" style="text-align:center;">
                                <div><a class="descriptionIcon"><img src="img/ico1.png" style="width:100px; height: 100px"></a></div>
                                <h3 class="descriptionTitle">{@$config.music_title1@}</h3>
                                <div class="description">
                                    {@$config.music_description1@}
                                </div>
                            </div>
                            <div class="col-md-2" style="text-align:center;">
                                <div><a class="descriptionIcon"><img src="img/ico2.png" style="width:100px; height: 100px"></a></div>
                                <h3 class="descriptionTitle">{@$config.music_title2@}</h3>
                                <div class="description">
                                    {@$config.music_description2@}
                                </div>
                            </div>
                            <div class="col-md-2" style="text-align:center;">
                                <div><a class="descriptionIcon"><img src="img/ico3.png" style="width:100px; height: 100px"></a></div>
                                <h3 class="descriptionTitle">{@$config.music_title3@}</h3>
                                <div class="description">
                                    {@$config.music_description3@}
                                </div>
                            </div>
                            <div class="col-md-2" style="text-align:center;">
                                <div><a class="descriptionIcon"><img src="img/ico4.png" style="width:100px; height: 100px"></a></div>
                                <h3 class="descriptionTitle">{@$config.music_title4@}</h3>
                                <div class="description">
                                {@$config.music_description4@}
                                </div>
                            </div>
                            <div class="col-md-2" style="text-align:center;">
                                <div><a class="descriptionIcon"><img src="img/ico5.png" style="width:100px; height: 100px"></a></div>
                                <h3 class="descriptionTitle">{@$config.music_title5@}</h3>
                                <div class="description">
                                {@$config.music_description5@}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="teacher">
                    <div class="container paddingrow">
                        <div class="row teacher">
                        专注 . 极致 . 用心 . 严谨
                        </div>
                        <div class="row teacher">
                        带给孩子最动听的儿童音乐
                        </div>
                        <div class="row teacher">
                        玩的是<span style="font-size:50px">快乐</span>，学的是<span style="font-size:50px">知识</span>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="activity">
                    <div class="container paddingrow">
                        <div class="row">
                            <div class="col-md-3" style="padding:20px">
                                <img src="{@$config.index_photo1@}" width="240px;"/>
                            </div>
                            <div class="col-md-3" style="padding:20px">
                                <img src="{@$config.index_photo2@}" width="240px"/>
                            </div>
                            <div class="col-md-3" style="padding:20px">
                                <img src="{@$config.index_photo3@}" width="240px"/>
                            </div>
                            <div class="col-md-3" style="padding:20px">
                                <img src="{@$config.index_photo4@}" width="240px"/>
                            </div>
                        </div>
                        <div  style="text-align: center;margin:20px;">
                            <a href="/photo"><span class="more">更多图片</span></a>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="about">
                    <div class="container paddingrow">
                        <div class="row">
                            <div class="col-md-6 padding">
                                <dl class="dl-horizontal">
                                    <dd><img src="./img/qr.png" style="width:120px;height:120px"></dd>
                                    <dd>乐开音乐专注于0-12岁儿童音乐教育</dd>
                                    <dd>致力于提升全体国民儿童的音乐素养</dd>
                                    <dd>带给孩子最具时代审美和气质的儿童音乐</dd>
                                    <dd>让亿万儿童享有更具艺术高度的音乐教育服务</dd>
                                </dl>
                            </div>
                            <div class="col-md-6 padding" style="font-color:#313030">
                                <dl class="dl-horizontal">
                                    <dt><a>名称：</a></dt><dd>{@$config.name@}</dd>
                                    <dt><a>网址：</a></dt><dd>http://{@$config.host@}</dd>
                                    <dt><a>地址：</a></dt><dd><a href="/map.html" target="_blank">{@$config.address@}（打开地图）</a></dd>
                                    <dt><a>邮箱：</a></dt><dd>{@$config.email@}</dd>
                                    <dt><a>手机：</a></dt><dd><a href="tel:{@$config.mobile@}">{@$config.mobile@}</a></dd>
                                    <dt><a>传真：</a></dt><dd>{@$config.fax@}</dd>
                                    <dt><a>Q Q： </a></dt><dd>{@$config.qq@}</dd>
                                    <dt><a>微信： </a></dt><dd>lekaimusic</dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--标签页 end-->
    <!--固定start-->
    <div class="container">
        <div class="row paddingrow">
            <div class="col-md-6 padding">
                <h2>乐开作品</h2>
                <div id="content-music-player">
                    <div id="music-player">
                        <div id="music-player-header">
                            <h2 class="inon"></h2>
                            <h3></h3>
                        </div>
                        <div style="width: 0px; height: 0px;" id="jquery_jplayer_1" class="jp-jplayer"><img style="width: 0px; height: 0px; display: none;" id="jp_poster_0"><audio src="8082_files/%2520--%2520Opening.mp3" preload="metadata" id="jp_audio_0"></audio></div>

                        <div id="jp_container_1" class="jp-audio" width="400" height="64">
                            <div class="jp-type-playlist">
                                <div class="jp-gui jp-interface">
                                    <div class="jp-controls">
                                        <a href="javascript:;" class="jp-previous" tabindex="1">previous</a>
                                        <a href="javascript:;" class="jp-play" tabindex="1">play</a>
                                        <a style="display: none;" href="javascript:;" class="jp-pause" tabindex="1">pause</a>
                                        <a href="javascript:;" class="jp-next" tabindex="1">next</a>
                                    </div>
                                    <div class="jp-progress-container">
                                        <div class="jp-progress">
                                            <div style="width: 100%;" class="jp-seek-bar">
                                                <div style="overflow: hidden; width: 0%;" class="jp-play-bar"><span class="jp-play-bar-knob"></span></div>
                                            </div>
                                        </div>
                                        <div class="jp-current-time">00:00</div>
                                    </div>
                                    <div class="jp-volume-controls">
                                        <a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a>
                                        <a style="display: none;" href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a>
                                        <div class="jp-volume-bar">
                                            <div style="width: 80%;" class="jp-volume-bar-value"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jp-playlist">
                                    <ul style="display: block;">
                                    {@foreach from=$caseList item=item @}
                                        <li class="jp-playlist-current">
                                            <div>
                                                <a style="display: none;" href="javascript:;" class="jp-playlist-item-remove">×</a>
                                                <a href="javascript:;" class="jp-playlist-item jp-playlist-current" tabindex="1">{@$item.name@}<span></span></a>
                                             </div>
                                        </li>
                                    {@/foreach@}
                                   </ul>
                                </div>
                                <span class="shadow"></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div style="text-align: center;margin:20px;">
                    <a href="/case"><span class="more">更多作品</span></a>
                </div>

                <script type="text/javascript">
                    var playermp3s = [
                    {@foreach from=$caseList item=item @}
                        {title: '{@$item.name@}<span></span>',
                        mp3: '{@$item.src@}'},
                    {@/foreach@}
                    ];
                </script>
            </div>
            <div class="col-md-6 padding">
                <h2>乐开文化</h2>
                {@foreach from=$newsList item=news@}
                    <div style="line-height:200%;font-size:20px">{@$news.add_time@}</div>
                    <h4>{@$news.title|truncate:30:"...":true@}</h4>
                    <p style="margin:5px 0;line-height:150%;">{@$news.description@}<span><a href="/news/detail/id/{@$news.id@}">>>查看详情</a></span></p>
                    <hr/>
                {@/foreach@}
                <div style="text-align: center;margin:20px;">
                <a href="/news"><span class="more">更多文化</span></a>
                </div>
            </div>
        </div>
    </div>
    <!--固定end-->
    <div style="background-color: #a32b2d">
        <div class="container text-center">
        <h3 style="color: white;padding: 15px">乐开儿童音乐王国全国加盟，即将开启，敬请期待</h3>
        </div>
    </div>
    <div class="modal fade" id="videoModal" tabindex="-1">
        <div class="modal-dialog" role="document" style="width: auto;">
            <div class="modal-content">
                <div class="modal-body">
                    <video id="videoSource" controls="controls" style="width: 100%">
                        <source src="{@$config.video@}" type="video/mp4">
                        你的浏览器不支持该视频播放！
                    </video>
                </div>
            </div>
        </div>
    </div>

{@include 'footer.phtml'@}

<script>
    $(function () {
        var video = document.getElementById('videoSource');
        $('#videoModal').on('hide.bs.modal', function () {
            video.pause();
        })
        $('#videoModal').on('shown.bs.modal', function () {
            video.play();
        })
    });
</script>