<!--header-->
{@include 'header.phtml'@}
<!--/header-->

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <!--menu-->
            {@include 'menu.phtml'@}
            <!--/menu-->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h2 class="sub-header">修改文章</h2>
            <div class="row placeholders">
                <a href="/admin/news/index"><button class="btn btn-default">返回</button></a>
            </div>
            <div class="table-responsive">
                <form id='form' enctype="multipart/form-data" method="post" action="/admin/news/save">
                    <table class="table table-striped">
                        <tr>
                            <td>文章名称</td>
                            <td>
                                <input name="id" type="hidden" value='{@$news.id@}'/>
                                <input name="title" type="text" value='{@$news.title@}'/>
                            </td>
                        </tr>
                        <tr>
                        <tr>
                            <td>文章类型</td>
                            <td><select name="type">
                                    {@foreach from=$newsCategory item=item@}
                                    <option value="{@$item.id@}" {@if $news.type eq $item.id@}selected{@/if@}>{@$item.name@}</option>
                                    {@/foreach@}
                                </select></td>
                        </tr>
                        <tr>
                            <td>排序</td>
                            <td><input name="order" type="text" value='{@$news.order@}'/></td>
                        </tr>
                        <tr>
                            <td>文章描述</td>
                            <td><textarea name="description" rows="5" cols="80">{@$news.description@}</textarea></td>
                        </tr>
                        <tr>
                            <td>文章来源</td>
                            <td><input name="source" type="text" value='{@$news.source@}'/></td>
                        </tr>
                        <tr>
                            <td>链接地址</td>
                            <td><input name="link" type="text" value='{@$news.link@}'/></td>
                        </tr>
                        <tr>
                            <td>文章内容</td>
                            <td>
                                <script id="content" name="content" style="width:600px;height:400px" type="text/plain">
                                    {@$news.content@}
                                </script>
                            </td>
                        </tr>
                        <tr>
                            <td colspan=2>
                                <input id='submit' type="submit" value="提交"/>
                                <input id='reset' type="reset" value="重置"/>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    //加载公式编辑器
    var this_title = UE.getEditor('content');

    //试题添加
    $('#submit').click(function () {
        var title = this_title.overflow ? '--overflow--' : this_title.getContent();
        if (title == '') {
            alert('请填写内容！');
            return false;
        } else if (title == '--overflow--') {
            alert('内容字数超限！');
            return false;
        }
        $('#form').submit();
    });

    //重置
    $('#reset').click(function () {
        this_title.setContent('');
    });

</script>
<!--footer-->
{@include 'footer.phtml'@}
<!--/footer-->
