{@include 'header.phtml'@}

<div style="background-color:#e7efef">
    <div class="container">
        <img class="carousel-inner img-responsive" src="http://{@$config.host@}/images/detail/cause.png">
    </div>
</div>
<!--mainContent start-->
<div class="container">
    <h3 style="line-height: 300%">乐开风采</h3>
    <div class="row">
        {@foreach from=$list item=photo@}
        <div class="thumbnail col-md-4 col-xs-11">
            <div>
                <img class="carousel-inner img-responsive"  src="http://{@$config.host@}/{@$photo.img@}">
            </div>
            <div class="text-center">{@$photo.title@}</div>
            <div style="line-height: 150%;color: #cccccc">
                {@$photo.content@}
            </div>
        </div>
        {@/foreach@}
    </div>
</div>
<!--mainContent end-->

{@include 'footer.phtml'@}

<script src="./js/jquery-3.2.1.min.js"></script>
<script src="./js/bootstrap.min.js"></script>


