{@include 'header.phtml'@}

<!--mainContent start-->
<div class="mainContent">
    <div class="container content">
        <!--标题-->
        <div class="pageTit">乐开风采</div>
        <!--/标题-->

        <div id="masonry" class="container-fluid">
        </div>

        <div id="masonry_ghost" class="hide">
            {@foreach from=$list item=photo@}
            <div class="thumbnail col-md-3">
                <div class="imgs">
                    <input type="hidden" value="{@$photo.img@}">
                </div>
                <div class="caption">
                    <div class="title_1">{@$photo.title@}</div>
                    <div class="content_1">
                        {@$photo.content@}
                    </div>
                    <div class="author">by 乐开音乐</div>
                </div>
            </div>
            {@/foreach@}
        </div>

    </div>
</div>
<!--mainContent end-->

<div style="background-color: #EEEEEE">
    <div class="container" style="padding: 20px">
        ©2017 {@$config.name@}版权所有 沪ICP备15002392号 24小时热线电话：{@$config.mobile@}
        <span style="float:right">
            <a href="/job">加入我们</a>
        </span>
    </div>
</div>

<script src="./js/jquery-3.2.1.min.js"></script>
<script src="./js/bootstrap.min.js"></script>
<script src="./js/lightbox.min.js"></script>
<script src="./js/masonry.pkgd.min.js"></script>
<script src="./js/imagesloaded.pkgd.min.js"></script>

<script>
    $(function () {

        var ghostNode = $('#masonry_ghost').find('.thumbnail'), i, ghostIndexArray = [];
        var ghostCount = ghostNode.length;
        for (i = 0; i < ghostCount; i++) {
            ghostIndexArray[i] = i;
        }
        ghostIndexArray.sort(function (a, b) {
            if (Math.random() > 0.5) {
                return a - b;
            } else {
                return b - a;
            }
        });

        var currentIndex = 0;
        var masNode = $('#masonry');
        var imagesLoading = false;

        function getNewItems() {
            var newItemContainer = $('<div/>');
            for (var i = 0; i < 6; i++) {
                if (currentIndex < ghostCount) {
                    newItemContainer.append(ghostNode.get(ghostIndexArray[currentIndex]));
                    currentIndex++;
                }
            }
            return newItemContainer.find('.thumbnail');
        }

        function processNewItems(items) {
            items.each(function () {
                var $this = $(this);
                var imgsNode = $this.find('.imgs');
                var title = $this.find('.title_1').text();
                var author = $this.find('.author').text();
                title += '&nbsp;&nbsp;(' + author + ')';
                var lightboxName = 'lightbox_'; // + imgNames[0];

                var imgNames = imgsNode.find('input[type=hidden]').val().split(',');
                $.each(imgNames, function (index, item) {
                    imgsNode.append('<a href="' + item + '" data-lightbox="' + lightboxName + '" title="' + title + '"><img src="' + item + '" /></a>');
                });
            });
        }

        function initMasonry() {
            var items = getNewItems().css('opacity', 0);
            processNewItems(items);
            masNode.append(items);

            imagesLoading = true;
            items.imagesLoaded(function () {
                imagesLoading = false;
                items.css('opacity', 1);
                masNode.masonry({
                    itemSelector: '.thumbnail',
                    isFitWidth: true
                });
            });
        }

        function appendToMasonry() {
            var items = getNewItems().css('opacity', 0);
            processNewItems(items);
            masNode.append(items);

            imagesLoading = true;
            items.imagesLoaded(function () {
                imagesLoading = false;
                items.css('opacity', 1);
                masNode.masonry('appended', items);
            });
        }

        initMasonry();

        $(window).scroll(function () {

            if ($(document).height() - $(window).height() - $(document).scrollTop() < 10) {

                if (!imagesLoading) {
                    appendToMasonry();
                }

            }

        });

    });
</script>
</body>
</html>

