{@include 'header.phtml'@}

<div style="background-color:#e7efef;margin-top: 95px;">
    <img class="carousel-inner img-responsive" src="http://{@$config.host@}/{@$pageConfig.banner@}">
</div>
<!--mainContent start-->
<div class="container" style="padding: 20px 0">
    <h3 style="line-height: 300%">乐开风采</h3>
    <div class="row">
        {@foreach from=$list item=photo@}
        <div class="thumbnail col-md-4 col-xs-11">
            <div>
                <img class="carousel-inner img-responsive"  src="http://{@$config.host@}/{@$photo.img@}">
            </div>
            <div class="text-center" style="padding: 10px">{@$photo.title@}</div>
            <div style="line-height: 150%;color: #cccccc;padding: 10px;">{@$photo.content@}</div>
        </div>
        {@/foreach@}
    </div>
</div>
<!--mainContent end-->

{@include 'footer.phtml'@}


